/* Akademîya Aram Tîgran — DİL PAKETİ (otomatik üretilir: tools/dil-entegre.js)
 * AAT_TX        : uygulama metinleri — anahtar = kaynaktaki Kurmancî metin
 *   .ku         : Kurmancî düzeltmeleri (akademisyen raporu)
 *   .zza         : Zazakî karşılıkları (akademisyen raporu)
 *   .tr         : Türkçe karşılıkları
 * AAT_SITE      : ana sayfa (site) metinleri — anahtar = SITE_T anahtarı
 * AAT_SITE_AREA : sanat alanı adları (site)
 * AAT_ZAROK     : Akademiya Zarokan veli uygulaması (anahtar = zarok/app sözlük anahtarı)
 * AAT_ZAROK_SITE: Akademiya Zarokan tanıtım/başvuru sayfası
 * Elle düzenlemeyin; rapor JSON'larını tools/dil-entegre.js ile birleştirin. */
window.AAT_TX={"ku":{},"zza":{},"tr":{"⚠ Pel pir mezin e (max 600KB)":"⚠ Dosya çok büyük (en fazla 600KB)",
"⚠ Navê belgeyê pêwîst e":"⚠ Belge adı gerekli",
"Belgeyên pêwîst":"İstenen belgeler",
"Dêûbav divê her belgeyekê cuda bar bike. Heke pelekî şablonê (forma ku were dagirtin) zêde bikî, li ser malperê tê daxistin.":"Veli her belgeyi ayrı yükler. Bir şablon dosyası (doldurulacak form) eklerseniz sitede indirilebilir.",
"Navê belgeyê (mînak: Wêneya nasnameyê)":"Belge adı (ör. Kimlik fotoğrafı)",
"📎 Pelê şablonê (vebijarkî — PDF an wêne)":"📎 Şablon dosyası (isteğe bağlı — PDF veya görsel)",
"Belgeyê zêde bike":"Belge ekle",
"⚠ Ev mamoste berê hatiye girêdan":"⚠ Bu öğretmen zaten bağlı",
"✅ Mamosteyê akademiyê hate girêdan":"✅ Akademi öğretmeni bağlandı",
"Mamosteyê akademiyê? Jimara wî/wê (vebijarkî)":"Akademi öğretmeni mi? Numarası (isteğe bağlı)",
"Hesabê nû nayê vekirin: mamoste bi jimare û şîfreya xwe ya akademiyê dikeve sepana zarokan.":"Yeni hesap açılmaz: öğretmen çocuk uygulamasına kendi akademi numarası ve şifresiyle girer.",
"Akademî":"Akademi",
"Xwendekar tune":"Öğrenci yok",
"Herî kêm 8 tîp":"En az 8 karakter",
"Tîpa mezin lazim e":"Büyük harf gerekli",
"Hejmar lazim e":"Rakam gerekli",
"Hesabê te û hemû daneyên te DÊ BI TEVAHÎ bên jêbirin. Ev kar venagere. Berdewam bikî?":"Hesabınız ve tüm verileriniz KALICI OLARAK silinecek. Bu işlem geri alınamaz. Devam edilsin mi?",
"JÊBIRIN":"SİL",
"✖ Jêbirin hate betalkirin":"✖ Silme iptal edildi",
"✅ Hesab hate jêbirin":"✅ Hesap silindi",
"⚠ Çewtî çêbû — bi rêvebir re têkilî daynin":"⚠ Hata oluştu — yöneticiyle iletişime geçin",
"Ji bo erêkirinê \"{0}\" binivîse:":"Onaylamak için \"{0}\" yazın:",
"Bûrsa %75":"%75 Burs",
"Bûrsa %50":"%50 Burs",
"Bûrsa %25":"%25 Burs",
"QR":"QR",
"Bûrs":"Burs",
"Not":"Not",
"Rapor":"Rapor",
"Dûşem":"Pazartesi",
"Sêşem":"Salı",
"Çarşem":"Çarşamba",
"Pêncşem":"Perşembe",
"Înî":"Cuma",
"Şemî":"Cumartesi",
"Yekşem":"Pazar",
"Amadebûna Dersê":"Ders Yoklaması",
"{0}, em hemû kêfxweş in!":"{0}, hepimiz çok mutluyuz!",
"Em hemû kêfxweş in!":"Hepimiz çok mutluyuz!",
"Şîfreya nû hat şandin bo:":"Yeni şifre gönderildi:",
"Emaila xwe kontrol bike û bi şîfreya nû têkeve.":"E-postanızı kontrol edin ve yeni şifreyle giriş yapın.",
"Şîfreya {0} hate guhertin.":"{0} için şifre sıfırlandı.",
"Şîfreya nû ji bikarhêner re bide.":"Yeni şifreyi kullanıcıya doğrudan iletin.",
"Fotokopiya Nasnameyê":"Kimlik fotokopisi",
"Belgeya Nasnameya Sivîl / Jidayikbûnê":"Nüfus / Doğum belgesi",
"Belgeya Rûniştinê":"İkametgâh belgesi",
"Wêne (2 heb)":"Fotoğraf (2 adet)",
"✅ Mamoste Tescîl Bû":"✅ Öğretmen Kaydedildi",
"pel":"dosya",
"⚠ Vîdyo pir mezin e (max {0}MB)":"⚠ Video çok büyük (en fazla {0}MB)",
"Orîjînal":"Orijinal",
"werger (vebijarkî — dema zimanê malperê tê guhertin tê nîşandan). Ger KU vala bimîne, sernav/nivîsa sereke ev dibe.":"çeviri (isteğe bağlı — site dili değişince gösterilir). KU boş bırakılırsa ana başlık/metin bu olur.",
"Kalîte":"Kalite",
"Jêrnivîs (.srt/.vtt)":"Altyazı (.srt/.vtt)",
"Karta {0} Tescîl Bû":"{0} Kartı Kaydedildi",
"Karta {0} Tescîl Bike":"{0} Kartı Kaydet",
"Danasîn...":"Hakkında...",
"📄 PDF":"📄 PDF",
"Lîsteya Serlêdanan":"Başvuru Listesi",
"serlêdan":"başvuru",
"Rewş":"Durum",
"Serlêdana Xwendekariyê":"Öğrenci Başvurusu",
"Belge":"Belge",
"ji sîstemê veke":"sistemden açın",
"Profîl hate nûkirin":"Profil güncellendi",
"Karûbarên Xwendekaran / Rêveberî":"Öğrenci İşleri / Yönetim",
"roj":"gün",
"carî":"kez",
"Xwendekarên Tevahî":"Toplam Öğrenci",
"Navê Xwendekarê":"Öğrenci Adı",
"Jm. Xwendekarê":"Öğrenci No",
"Tevahî":"Tam",
"Tunebûn (roj)":"Devamsızlık (gün)",
"Pirsa Nû":"Yeni Soru",
"Amadebûna QR":"QR Yoklama",
"PDF, Word, PPT, Wêne, Vîdyo":"PDF, Word, PPT, Görsel, Video",
"Wêne nehat barkirin":"Fotoğraf yüklenemedi",
"E-peyam ne rast e":"E-posta geçersiz",
"Tomarkirin serneket":"Kaydedilemedi",
"Nav, jimare û qad ji aliyê karûbarên xwendekaran ve tên guhertin. Yên din tu bi xwe dagirî.":"Ad, numara ve alan öğrenci işleri tarafından değiştirilir. Diğerlerini kendiniz doldurabilirsiniz.",
"Wêneyê biguherîne":"Fotoğrafı değiştir",
"Wêne zêde bike":"Fotoğraf ekle",
"Navnîşan…":"Adres…",
"Kurte danasîn…":"Kısa tanıtım…",
"Li benda şopa tiliyê / naskirina rû…":"Parmak izi / Yüz tanıma bekleniyor…",
"Şopa tiliyê, Face ID, PIN":"Parmak izi, Face ID, PIN",
"nû":"yeni",
"Hûn ketin vê dersê":"Bu derse katıldınız",
"Şîfre veşêre":"Şifreyi gizle",
"Şîfre nîşan bide":"Şifreyi göster",
"Ji bo tescîla dersê QR-a min":"Ders yoklaması için QR kodum",
"Girêdan vegeriya":"Bağlantı yeniden kuruldu",
"Girêdan tune – moda derhêl":"Bağlantı yok – çevrimdışı mod",
"Xweş hatî: ":"Hoş geldin: ",
"Serketî":"Başarılı",
"Pêşkeve":"Gelişiyor",
"Bala xwe bide":"Dikkat etmeli",
"Pir baş":"Çok iyi",
"Bişopîne":"Takip et",
"Bihar":"İlkbahar",
"Payîz":"Sonbahar",
"Havîn":"Yaz",
"Zivistan":"Kış",
"📥 Kart tê amadekirin…":"📥 Kart hazırlanıyor…",
"⚠ Ji kerema xwe dîsa biceribîne (hîn bar dibe)":"⚠ Lütfen tekrar deneyin (hâlâ yükleniyor)",
"⚠ Dakêşan bi ser neket":"⚠ İndirme başarısız",
"✅ Kart hat tomarkirin (HD)":"✅ Kart kaydedildi (HD)",
"✅ PDF ya çapxaneyê hat tomarkirin":"✅ Matbaa PDF'i kaydedildi",
"Siyaseta Nepenîtiyê":"Gizlilik Politikası",
"Akademîya Aram Tîgran — Nepenîtiya daneyên we ji bo me giring e.\n\n• Agahiyên xwendekar û mamosteyên tenê ji bo rêveberiya dibistanê têne bikaranîn.\n• Daneyên we bi partiyên sêyem re nayên parve kirin.\n• Daneyên Firebase-ê bi protokolên ewlehiyê yên SSL/TLS têne parastin.\n• Wêneyên barkirin tenê di Firebase Storage de têne hilanîn.\n• Hûn dikarin daxwaza jêbirina daneyan bikin: info@aramtigran.edu":"Akademîya Aram Tîgran — Verilerinizin gizliliği bizim için önemlidir.\n\n• Öğrenci ve öğretmen bilgileri yalnızca akademi yönetimi için kullanılır.\n• Verileriniz üçüncü taraflarla paylaşılmaz.\n• Firebase verileri SSL/TLS şifrelemesiyle korunur.\n• Yüklenen fotoğraflar yalnızca Firebase Storage'da saklanır.\n• Veri silme talepleri: info@aramtigran.edu",
"Şertên Bikaranînê":"Kullanım Koşulları",
"Akademîya Aram Tîgran — Şertên Bikaranînê\n\n• Ev sepet tenê ji bo xwendekar û mamosteyên Akademîya Aram Tîgran e.\n• Bikaranîna ne rewa ya hesabê qedexe ye.\n• Daneyên têketina we nepenî ne; wan parve nekin.\n• Akademî mafê guhertina sîstemê dihêle.\n• Pirsên: info@aramtigran.edu":"Akademîya Aram Tîgran — Kullanım Koşulları\n\n• Bu uygulama yalnızca Akademîya Aram Tîgran'ın kayıtlı öğrenci ve öğretmenleri içindir.\n• Hesapların yetkisiz kullanımı kesinlikle yasaktır.\n• Giriş bilgilerinizi gizli tutun; kimseyle paylaşmayın.\n• Akademi sistemi değiştirme hakkını saklı tutar.\n• Sorular: info@aramtigran.edu",
"Guhertinên Nû":"Yenilikler",
"v4.1 (2026)\n• Tema ronahî/tarî bi tevahî hevaheng\n• Rastkirina nivîsa nexuyayî (fîltera Qadan)\n• Jêbirina hesêb di nav sepanê de\n• App Check + amadekariya Play Store\n• Rastkirinên rapora \"Hemû Qadan\"\n\nv4.0 (2025)\n• Piştgiriya PWA ya tevahî — zêde bike ser ekrana sereke\n• iOS safe-area, splash destpêkê\n• Firebase Auth, Storage, Offline\n• Haptic feedback, Share API\n• Baştirkirinên xwesteka gihîştinê\n• Ekranên rewşa vala\n• Performans: React.memo, useMemo\n• Ewlehî: CSP, pêşgiriya XSS\n\nv3.0\n• Service Worker — xebata offline\n• Tema tarî / ronahî\n• Baştirkirina xwendina QR\n• Pirrzimanî (Kurmancî/Zazakî/Tirkî/English)":"v4.1 (2026)\n• Tamamen tutarlı açık/koyu tema\n• Okunamayan metin düzeltildi (Alan filtresi)\n• Uygulama içinden hesap silme\n• App Check + Play Store hazırlığı\n• \"Tüm Alanlar\" rapor düzeltmeleri\n\nv4.0 (2025)\n• Tam PWA desteği — ana ekrana ekle\n• iOS güvenli alan, açılış ekranları\n• Firebase Auth, Storage, çevrimdışı kalıcılık\n• Dokunsal geri bildirim, Paylaşım API\n• Erişilebilirlik iyileştirmeleri (WCAG 2.1)\n• Boş durum ekranları\n• Performans: React.memo, useMemo\n• Güvenlik: CSP, XSS önleme\n\nv3.0\n• Service Worker — çevrimdışı çalışma\n• Koyu / açık tema\n• QR okuma iyileştirmeleri\n• Çok dillilik (Kurmancî/Zazakî/Türkçe/English)",
"Em daneyên we ji bo rêveberiya akademiyê bikar tînin. Têketina we razîbûnê nîşan dide.":"Verilerinizi akademi yönetimi amacıyla kullanıyoruz. Giriş yapmanız Gizlilik Politikamızı kabul ettiğiniz anlamına gelir.",
"Qebûl bike":"Kabul et",
"Sînema":"Sinema",
"Sînema û Dîroka Fîlimê":"Sinema ve Film Tarihi",
"Muzîk":"Müzik",
"Teoriya Muzîkê û Performans":"Müzik Teorisi ve Performans",
"Şano":"Tiyatro",
"Hunera Şanoyê û Performans":"Tiyatro Sanatı ve Performans",
"Dans":"Dans",
"Dansên Klasîk û Modern":"Klasik ve Modern Dans",
"Wêje":"Edebiyat",
"Nivîsandina Afirîner û Wêje":"Yaratıcı Yazarlık ve Edebiyat",
"Wênesazî":"Resim",
"Wênesazî û Hunera Dîtbarî":"Resim ve Görsel Sanatlar",
"Hemû Xwendekar":"Tüm Öğrenciler",
"Dersên Hevpar ên Akademiyê":"Akademi Ortak Dersleri",
"AKADEMÎYA ARAM TÎGRAN":"ARAM TİGRAN AKADEMİSİ",
"Pergala Rêveberiya Zanistê":"Yönetim Bilgi Sistemi",
"Cureya têketinê hilbijêre":"Giriş türünü seç",
"Xwendekar":"Öğrenci",
"Jimara xwendekarê":"Öğrenci numarası",
"Mamoste":"Öğretmen",
"Jimara mamoste":"Öğretmen numarası",
"Jimara Xwendekarê":"Öğrenci Numarası",
"Jimara Mamoste":"Öğretmen Numarası",
"Şîfre":"Şifre",
"Têkeve":"Giriş Yap",
"Şîfre ji bîr kir?":"Şifremi unuttum?",
"Hejmar an şîfre xelet e.":"Numara veya şifre hatalı.",
"Panela Rêveberiyê":"Yönetim Paneli",
"Qadên Hunerê":"Sanat Alanları",
"Peywirên Bendewar":"Bekleyen Onaylar",
"Bernameyên Çalak":"Aktif Programlar",
"Xwendekar Tescîl Bike":"Öğrenci Kaydet",
"Mamoste Tescîl Bike":"Öğretmen Kaydet",
"Bernameya Qadê":"Alan Programı",
"Xwendekarên Qadê":"Alan Öğrencileri",
"Mamoste / Hînkar":"Öğretmenler",
"Bernameya Dersê":"Ders Programı",
"Xwendekarekî Nû":"Yeni Öğrenci",
"Mamosteyekî Nû":"Yeni Öğretmen",
"Dersekî Nû":"Yeni Ders",
"Nav û Nasname":"Ad ve Soyad",
"Qada Hunerê":"Sanat Alanı",
"Sala Tescîlê":"Kayıt Yılı",
"Burs Tune":"Burs Yok",
"Bursê Tevahî":"Tam Burs",
"Jimara Xwendekarê (Pêşdîtin)":"Öğrenci Numarası (Önizleme)",
"Navê Bikarhêner":"Kullanıcı Adı",
"Şîfre (destpêkê: 1234)":"Şifre (varsayılan: 1234)",
"Roj":"Gün",
"Navê Dersê":"Ders Adı",
"Destpêk":"Başlangıç",
"Dawî":"Bitiş",
"Cih":"Yer",
"Bernameyê Zêde Bike":"Programa Ekle",
"Bernameya Hefteyê":"Haftalık Program",
"Ragihandin":"Duyurular",
"Ragihandinek Bişîne":"Duyuru Gönder",
"Armanc":"Hedef",
"Sernav":"Başlık",
"Peyam":"Mesaj",
"Bişîne":"Gönder",
"Xwendekarên Min":"Öğrencilerim",
"Dersa Çalak":"Aktif Ders",
"Berdewam e":"Devam ediyor",
"Bernameya Îroyîn":"Bugünkü Program",
"Dersên Îroyîn":"Bugünkü Dersler",
"QR Bixwîne":"QR Okut",
"Lîsteya Amadebûnê":"Yoklama Listesi",
"Beşdarbu":"Geldi",
"Tunebû":"Gelmedi",
"Dereng":"Geç",
"Tomar bike":"Kaydet",
"Amadekarî hate tomarkirin":"Yoklama kaydedildi!",
"Mal":"Ana Sayfa",
"Amadebûn":"Devam",
"Profîl":"Profil",
"QR-a Min":"QR Kodum",
"Bernameya Min":"Programım",
"Amadebûna Min":"Devam Durumum",
"Navgîna giştî":"Genel ortalama",
"Amadebûna Semesterê":"Dönem devamı",
"Rojan tunebûm":"Devamsız gün",
"Ji bo tescîla dersê ji mamosteyê re bixwîne":"Derse kaydolmak için öğretmenine göster",
"QR Xwendekar Bixwîne":"Öğrenci QR Okut",
"Koda QR ya xwendekarê bixwîne":"Öğrencinin QR kodunu okut",
"Tescîl kir":"Kaydedildi",
"Xwendekar nehat dîtin":"Öğrenci bulunamadı",
"Qediya":"Tamamlandı",
"Çalak":"Aktif",
"Çaverê":"Bekliyor",
"Bername":"Program",
"Derkeve":"Çıkış",
"Dakêşin":"İndir",
"Nûkirin":"Yenile",
"Şîfre ji Bîr Kir":"Şifremi Unuttum",
"Navnîşana E-Postê":"E-posta Adresi",
"Hejmara Têlefonê":"Telefon Numarası",
"Girêdana E-Postê Bişîne":"E-posta Bağlantısı Gönder",
"Koda SMS Bişîne":"SMS Kodu Gönder",
"Koda verastkirinê hat şandin!":"Doğrulama kodu gönderildi!",
"Koda Verastkirinê":"Doğrulama Kodu",
"Rast bike":"Doğrula",
"Şîfreya Nû":"Yeni Şifre",
"Şîfreya Nû Dubare Bike":"Yeni Şifreyi Tekrarla",
"Şîfreya Nû Tomar Bike":"Yeni Şifreyi Kaydet",
"Şîfre hate guhertin!":"Şifre değiştirildi!",
"Vegere":"Geri",
"Kod hat şandin →":"Kod gönderildi →",
"Karta Nasnameyê Çêke":"Kimlik Kartı Oluştur",
"Karta Xwendekarê":"Öğrenci Kimlik Kartı",
"Qad":"Alan",
"Sal":"Yıl",
"Çap Bike":"Kartı Yazdır",
"E-Posta":"E-posta",
"Dîroka Jidayikbûnê":"Doğum Tarihi",
"Navnîşan":"Adres",
"Danasîn":"Hakkında",
"Wêne Barkirin":"Fotoğraf Yükle",
"Agahiyên Profîlê":"Profil Bilgileri",
"Agahiyên Xwendekarê":"Öğrenci Bilgileri",
"Agahiyên Mamoste":"Öğretmen Bilgileri",
"Agahiyên Nasnameyê":"Kimlik Bilgileri",
"Jimara Nasnameyê":"Kimlik Numarası",
"Cihê Jidayikbûnê":"Doğum Yeri",
"Netewe":"Uyruk",
"Navê Dayikê":"Anne Adı",
"Navê Bavê":"Baba Adı",
"Belgeyên Serlêdanê":"Başvuru Belgeleri",
"Belge Barkirin":"Belge Yükle",
"Xwendekar Jê Bibe":"Öğrenciyi Sil",
"Mamoste Jê Bibe":"Öğretmeni Sil",
"Ders Jê Bibe":"Dersi Sil",
"Dersa Biguherîne":"Dersi Düzenle",
"Dersa Tomar Bike":"Dersi Kaydet",
"Piştrast bike?":"Emin misiniz?",
"Ev çalakî nayê paşvekirin.":"Bu işlem geri alınamaz.",
"Erê":"Evet",
"Na":"Hayır",
"Biguherîne":"Düzenle",
"Ne çalak":"Pasif",
"Hefteya":"Hafta",
"Encam":"Sonuçlar",
"Bigire":"Kapat",
"Betal bike":"İptal",
"Bigere":"Ara",
"Agahî tune":"Veri yok",
"Tê barkirin...":"Yükleniyor...",
"Çewtiyek çêbû":"Bir hata oluştu",
"Hat tomarkirin":"Kaydedildi",
"Îro":"Bugün",
"Hemû Qad":"Tüm Alanlar",
"Ders":"Dersler",
"Mîheng":"Ayarlar",
"Ankêt":"Anket",
"Hemû xwendekarên akademiyê dikarin beşdar bibin":"Tüm akademi öğrencileri katılabilir",
"Xwendekar Zêde Bike":"Öğrenci Ekle",
"Mamoste Zêde Bike":"Öğretmen Ekle",
"Dersa Hevpar Zêde Bike":"Ortak Ders Ekle",
"Hîn xwendekarên hevpar tune":"Henüz öğrenci yok",
"Hîn mamoste tune":"Henüz öğretmen yok",
"Hîn dersên hevpar tune":"Henüz ortak ders yok",
"Dersa Sereke":"Ana Ders",
"Dersên Zêde / Atolye":"Ek Ders / Atölye",
"Dersên Sereke":"Ana Dersler",
"Her hefte yek roj dubare dibe — tenê roj hilbijêre":"Her hafta seçilen günde tekrarlanır — düzenli haftalık ders",
"Tarîxên taybet yên vê dersê zêde bike — atolye, kurs, îmtîhan...":"Bu ders için özel tarihler ekle — atölye, kurs, sınav...",
"Tarîxên Dersê":"Ders Tarihleri",
"Hîn tarîx nehatiye zêdekirin":"Henüz tarih eklenmedi",
"Herî kêm yek tarîx zêde bike":"En az bir tarih ekle",
"Ev tarîx berê hatibû zêdekirin":"Bu tarih zaten eklenmiş",
"Dersa sereke tune":"Ana ders yok",
"Dersên zêde / atolye tune":"Ek ders / atölye yok",
"Atolye, kurs yan jî tarîxên taybet yên dersê li vir tomar bike":"Atölye, kurs veya özel tarihli dersleri buraya kaydet",
"Dersa Sereke Zêde Bike":"Ana Ders Ekle",
"Dersa Zêde Bike":"Ek Ders Ekle",
"Îroj":"Bugün",
"Borî":"Geçmiş",
"Bê":"Yaklaşan",
"Dersên Sereke — Heftane":"Ana Dersler — Haftalık",
"Zêde":"Ek",
"tarîx":"tarih",
"Tarîx":"Tarih",
"Têlefonê xwe veke · Kamera veke · Koda QR-ê bixwîne":"Telefonu aç · Kamerayı aç · QR kodu okut",
"Amadebûn bi xweber têt tomarkirin":"Yoklama otomatik kaydedilir",
"QR çıktısı için tarayıcıda popup iznine izin verin":"QR çıktısı için tarayıcıda açılır pencere (popup) iznini verin",
"Rojbûna te pîroz be! 🎉":"Doğum günün kutlu olsun! 🎉",
"Spas":"Teşekkürler",
"Jm. Xwendekar":"Öğr. No",
"Şîfre Ji Bîr Kir":"Şifremi Unuttum",
"Jimara Xwendekar / Mamoste":"Öğrenci / Öğretmen Numarası",
"Jimara xwe binivîse":"Numaranı yaz",
"⚠ Jimare nehat dîtin":"⚠ Numara bulunamadı",
"Berdewam bike":"Devam et",
"← Vegere":"← Geri dön",
"⚠ E-posta tomarkirî nîne. Ji rêveberê re bibêje.":"⚠ Kayıtlı e-posta yok. Yöneticiye bildir.",
"E-posta tê şandin...":"E-posta gönderiliyor...",
"✅ Girêdan hat şandin!":"✅ Bağlantı gönderildi!",
"Emaila xwe kontrol bike û girêdanê bitikîne da ku şîfreya nû saz bikî.":"E-postanı kontrol et ve yeni şifre belirlemek için bağlantıya tıkla.",
"E-posta şandin neçû. Rêveber têkilî bike.":"E-posta gönderilemedi. Yöneticiyle iletişime geç.",
"Rêveber şîfreyê sıfırla bike":"Yönetici şifre sıfırlama",
"Şîfreya Nû (Otomatîk)":"Yeni Şifre (Otomatik)",
"Ev şîfre ji bo têketinê bide bikarhêner":"Bu şifreyi giriş için kullanıcıya ver",
"Ev şîfreyê bide bikarhêner":"Bu şifreyi kullanıcıya verin",
"✅ Şîfre hate guhertin!":"✅ Şifre sıfırlandı!",
"Naha dikare bi şîfreya nû têkeve.":"Artık yeni şifreyle giriş yapabilir.",
"Jimarê binivîse...":"Numarayı yazın...",
"Şîfreya nû bê çêkirin û ji emailê re bê şandin":"Yeni şifre oluşturulup e-posta adresine gönderilecek",
"Şîfreya Nû Çêke û Bişîne":"Yeni Şifre Oluştur ve Gönder",
"Rêveber otomatîk şîfre saz dike":"Yönetici otomatik şifre belirler",
"✅ Şîfre Hat Şandin!":"✅ Şifre Gönderildi!",
"Vegerê Têketinê":"Girişe Dön",
"✅ Şîfre Hate Sifirkirin":"✅ Şifre Sıfırlandı",
"Şîfreya Nû (Tenê ji bo Admin)":"Yeni Şifre (Yalnızca Yönetici)",
"Xwendekar hate tescîlkirin":"Öğrenci başarıyla kaydedildi",
"Têketina Sîstemê":"Giriş Bilgileri",
"Navê Bikarhêner (Jimara Xwendekar)":"Kullanıcı Adı (Öğrenci No)",
"Şîfre (otomatîk)":"Şifre (otomatik)",
"Şîfre niha tomarkirin — dîsa nayê nîşandan.":"Bu şifreyi şimdi kaydedin — tekrar gösterilmeyecek.",
"Hemûyan Kopye Bike":"Tümünü Kopyala",
"Kopye bû!":"Kopyalandı!",
"Sînif":"Sınıf",
"Nav û e-peyam bes in. Wêne, têlefon, roja jidayikbûnê û navnîşan piştî ku şîfre gihîşt, ji aliyê xwendekar ve ji panela wî/wê tên dagirtin.":"Ad ve e-posta yeterlidir. Fotoğraf, telefon, doğum tarihi ve adres, öğrenci şifresini aldıktan sonra kendi panelinden doldurur.",
"belge hatine barkirin":"belge yüklendi",
"Mamoste hate tescîlkirin":"Öğretmen kaydedildi",
"Navê Bikarhêner (Jimara Mamoste)":"Kullanıcı Adı (Öğretmen No)",
"Kilkkirî":"Kilitli",
"Nav û e-peyam bes in. Wêne, têlefon, roja jidayikbûnê, navnîşan û danasîn ji aliyê mamoste ve ji panela wî/wê tên dagirtin.":"Ad ve e-posta yeterlidir. Fotoğraf, telefon, doğum tarihi, adres ve biyografi öğretmen tarafından kendi panelinden doldurulur.",
"Dersan tayîn bike (vebijarkî)":"Derslere ata (isteğe bağlı)",
"Ne diyar (hemû mamosteyên qadê dibînin)":"Atanmamış (alanın tüm öğretmenleri görür)",
"Mamosteyê Dersê (vebijarkî)":"Dersin Öğretmeni (isteğe bağlı)",
"Cîhaz sıfırlandı — nû têketin dikare bibe":"Cihaz sıfırlandı — yeni cihazdan giriş yapılabilir",
"Cîhaza Tomar Bûyî":"Kayıtlı Cihaz",
"— Hîn cîhaz tomar nebûye":"— Henüz kayıtlı cihaz yok",
"✅ Cîhaz tomar e":"✅ Cihaz kayıtlı",
"Cîhazê Sıfırla":"Cihazı Sıfırla",
"Şîfreya Firebase Auth NEHAT nûkirin. Çare: Firebase Console → Authentication → vî hesabî jê bibe; di têketina pêş de bixweber ji nû ve tê çêkirin.":"Firebase Auth şifresi GÜNCELLENEMEDİ. Çözüm: Firebase Console → Authentication → bu hesabı silin; bir sonraki girişte otomatik yeniden oluşturulur.",
"Şîfreya nû: ":"Yeni şifre:",
"Jimara":"Numara",
"🔒 veşartî — ya nû saz bike":"🔒 gizli — yenisini belirleyin",
"E-peyam di vê tomarê de tune — pêşî zêde bike":"Bu kayıtta e-posta yok — önce ekleyin",
"E-peyam neçû":"E-posta gönderilemedi",
"Hate şandin: ":"Gönderildi:",
"Şîfreya nû (vala = nayê guhertin)":"Yeni şifre (boş = değişmez)",
"Şîfreya nû çêke":"Yeni şifre oluştur",
"Rêveberî (Admin)":"Yönetici (Admin)",
"Desthilata tevahî ya panela rêveberiyê — wek hesabê 1000.":"Yönetici paneline tam yetki — 1000 numaralı hesapla aynı.",
"Dersên hevpar yên akademiyê hîn dikin":"Akademinin ortak derslerini verir",
"Dîk":"Dikey",
"Berwarî":"Yatay",
"⬇ Kart Dakêşe (HD)":"⬇ Kartı İndir (HD)",
"🖨 PDF ya Çapxaneyê (CR80 + bleed)":"🖨 Matbaa PDF'i (CR80 + taşma payı)",
"Hemû Mamoste":"Tüm Öğretmenler",
"Hemû":"Herkes",
"⚠ Sernav û peyam lazim e":"⚠ Başlık ve mesaj gerekli",
"⚠ Wergir hilbijêre":"⚠ Alıcı seçin",
"Peyam hate şandin":"Mesaj gönderildi",
"Qutiya Girtî":"Gelen Kutusu",
"Şandî":"Gönderilenler",
"Peyamek Nû":"Yeni Mesaj",
"Taybet":"Özel",
"Girseyî":"Toplu",
"Wergir":"Alıcı",
"Koma":"Grup",
"Nexwandî":"Okunmamış",
"Dosya / Wêne Zêde Bike":"Dosya / Fotoğraf Ekle",
"Jêbire":"Sil",
"Peyam were jêbirin?":"Bu mesaj silinsin mi?",
"🗑 Peyam hate jêbirin":"🗑 Mesaj silindi",
"Pêvekirin":"Ekler",
"Dakêşe":"İndir",
"Hilbijêre...":"Seçin...",
"💡 Pêşniyar/Gilî":"💡 Öneri/Şikâyet",
"💬 Peyam":"💬 Mesajlar",
"🗑 Hate jêbirin":"🗑 Silindi",
"Peyam tune":"Mesaj yok",
"Girseyî (Hemû Xwendekar)":"Toplu (Tüm Öğrenciler)",
"Hemû Xwendekarên Min":"Tüm Öğrencilerim",
"Ji":"Kimden",
"Bo":"Kime",
"Rêveber":"Yönetici",
"xwendekar":"öğrenci",
"Hemûyan":"Tümü",
"Sernav...":"Konu...",
"Peyamê binivîse...":"Mesajınızı yazın...",
"📰 Nûçeyên Malperê":"📰 Site Haberleri",
"Ev nûçe li ser rûpela sereke (malper) ji her kesî re xuya dibin.":"Bu haberler ana sayfada (sitede) herkese açık görünür.",
"Nivîs":"Metin",
"Girêdana YouTube (vebijarkî)":"YouTube bağlantısı (isteğe bağlı)",
"📷 Wêne zêde bike (çend jî dibe)":"📷 Fotoğraf ekle (birden fazla olabilir)",
"🎬 Vîdyo bar bike":"🎬 Video yükle",
"📤 Biweşîne":"📤 Yayınla",
"Nûçeyên weşandî":"Yayınlanan haberler",
"Hîn nûçe tune. Ya yekem biweşîne!":"Henüz haber yok. İlkini yayınlayın!",
"Jê bibe":"Sil",
"⚠ Sernav pêwîst e — bi kêmanî bi zimanekî (KU/ZZA/TR/EN)":"⚠ Başlık gerekli — en az bir dilde (KU/ZZA/TR/EN)",
"✅ Nûçe hate weşandin":"✅ Haber yayınlandı",
"❌ Çewtî — dîsa biceribîne":"❌ Hata — tekrar deneyin",
"⚠ Ji bo vîdyoyê Firebase Storage pêwîst e (Blaze)":"⚠ Video için Firebase Storage gerekli (Blaze)",
"Wêne tên barkirin":"Fotoğraflar yükleniyor",
"Vîdyo tê barkirin":"Video yükleniyor",
"⚠ Danişîna Firebase tune — derkeve û ji nû ve têkeve":"⚠ Firebase oturumu yok — çıkış yapıp tekrar giriş yapın",
"Qad (ji bo parzûna malperê)":"Alan (site filtresi için)",
"Giştî (hemû)":"Genel (tümü)",
"BERG":"KAPAK",
"Pêşdîtin berî weşandinê":"Yayınlamadan önce önizle",
"Pêşdîtin":"Önizleme",
"Giştî":"Genel",
"(sernav tune)":"(başlık yok)",
"Ji bo vî zimanî nivîs tune — mêvan dê guhertoya kurdî bibînin.":"Bu dil için metin yok — ziyaretçiler Kürtçe sürümü görecek.",
"Çapemenî":"Basın",
"Nûçeyên malperê birêve dibe":"Site haberlerini yönetir",
"Karûbarên Xwendekaran":"Öğrenci İşleri",
"Serlêdanên tomarkirinê birêve dibe":"Kayıt başvurularını yönetir",
"Kart hate tescîlkirin":"Kart başarıyla kaydedildi",
"Navê Bikarhêner (Jimare)":"Kullanıcı Adı (Numara)",
"Erk":"Görev",
"Kartê Tescîl Bike":"Kartı Kaydet",
"Şîfreya nû...":"Yeni şifre...",
"📇 Kartên Taybet":"📇 Özel Kartlar",
"Ev kart ji beşa MAMOSTE têkevin û tenê erka xwe dibînin.":"Bu kartlar ÖĞRETMEN girişinden girer ve yalnızca kendi görevlerini görür.",
"➕ Kartê Tescîl Bike":"➕ Kartı Kaydet",
"Kartên tescîlkirî":"Kayıtlı kartlar",
"Hîn kart tune.":"Henüz kart yok.",
"Malperê bibîne":"Siteyi görüntüle",
"🏛 Arşîva Malperê":"🏛 Site Arşivi",
"Van tomaran li ser rûpela sereke di beşa «Dîroka Akademiyê» de bi salan têne rêzkirin. Nûçeyên weşandî bixweber tên zêdekirin — li vir tenê bûyerên girîng ên salên borî binivîse.":"Bu kayıtlar ana sayfada «Akademinin Tarihi» bölümünde yıllara göre sıralanır. Yayınlanan haberler otomatik eklenir — burada yalnızca geçmiş yılların önemli olaylarını girin.",
"Sal *":"Yıl *",
"Dîrok (vebijarkî)":"Tarih (isteğe bağlı)",
"Nivîs (vebijarkî)":"Metin (isteğe bağlı)",
"Etîket (mînak: Damezrandin)":"Etiket (örn. Kuruluş)",
"📷 Wêne zêde bike (vebijarkî)":"📷 Fotoğraf ekle (isteğe bağlı)",
"💾 Tomar bike":"💾 Kaydet",
"💾 Nû bike":"💾 Güncelle",
"Tomarên arşîvê":"Arşiv kayıtları",
"Hîn tomar tune. Ya yekem zêde bike!":"Henüz kayıt yok. İlkini ekleyin!",
"⚠ Sal pêwîst e (mînak 2010)":"⚠ Yıl gerekli (örn. 2010)",
"⚠ Sernav pêwîst e — bi kêmanî bi zimanekî":"⚠ Başlık gerekli — en az bir dilde",
"✅ Tomar hate qeydkirin":"✅ Kaydedildi",
"Ev tomar were jêbirin?":"Bu kayıt silinsin mi?",
"Tomar tê guhertin":"Kayıt düzenleniyor",
"wergera (vebijarkî — dema zimanê malperê tê guhertin xuya dibe).":"çeviri (isteğe bağlı — site dili değişince gösterilir).",
"Qad (vebijarkî)":"Alan (isteğe bağlı)",
"Nûçeyên Malperê":"Site Haberleri",
"Arşîv":"Arşiv",
"Çapemenî · Edîtorê Malperê":"Basın · Site Editörü",
"Serlêdan":"Başvurular",
"Tescîl (Xwendekar/Mamoste)":"Kayıt (Öğrenci/Öğretmen)",
"Bername û Demsal":"Program ve Dönem",
"⚙️ Mîhengên Serlêdanê":"⚙️ Başvuru Ayarları",
"Serlêdan VEKIRÎ ye":"Başvurular AÇIK",
"Serlêdan GIRTÎ ye":"Başvurular KAPALI",
"Destpêk (vebijarkî)":"Başlangıç (isteğe bağlı)",
"Dawî (vebijarkî)":"Bitiş (isteğe bağlı)",
"Nîşeya li ser malperê (vebijarkî)":"Sitede gösterilecek not (isteğe bağlı)",
"✅ Hate tomarkirin":"✅ Kaydedildi",
"📄 Belgeyên Pêwîst":"📄 İstenen Belgeler",
"Ev belge li ser malperê xuya dibin; serlêder her yekê cuda bar dike.":"Bu belgeler sitede görünür; başvuran her birini ayrı yükler.",
"Navê belgeyê (ör. Forma Tomarkirinê)":"Belge adı (örn. Kayıt Formu)",
"📎 Şablona vala (wêne/PDF — vebijarkî)":"📎 Boş şablon (görsel/PDF — isteğe bağlı)",
"➕ Belgeyê Zêde Bike":"➕ Belge Ekle",
"Hîn belge nehatiye danîn.":"Henüz belge tanımlanmadı.",
"⚠ Nav pêwîst e":"⚠ Ad gerekli",
"⚠ Dosya pir mezin e (max ~600KB)":"⚠ Dosya çok büyük (en fazla ~600KB)",
"📋 Serlêdan":"📋 Başvurular",
"📄 Lîsteya PDF":"📄 PDF Listesi",
"Hîn serlêdan tune.":"Henüz başvuru yok.",
"Nû":"Yeni",
"Qebûl":"Kabul",
"Red":"Ret",
"✅ Qebûl û Tescîl":"✅ Kabul Et ve Kaydet",
"❌ Red bike":"❌ Reddet",
"Belgeyên barkirî":"Yüklenen belgeler",
"Têlefon":"Telefon",
"Roja jidayikbûnê":"Doğum tarihi",
"Nîşe":"Not",
"✅ Xwendekar Tescîl Bû":"✅ Öğrenci Kaydedildi",
"Van agahiyan bide xwendekar — ji beşa XWENDEKAR têkeve.":"Bu bilgileri öğrenciye verin — ÖĞRENCİ girişinden girer.",
"Berê tescîl bûye":"Zaten kayıtlı",
"❌ Çewtî":"❌ Hata",
"Tescîl":"Kaydet",
"E-peyam neçû — agahiyan bi destan bide":"E-posta gönderilemedi — bilgileri elden iletin",
"Agahiyên têketinê bi e-peyamê çûn: ":"Giriş bilgileri e-postayla gönderildi:",
"Jimara Xwendekar":"Öğrenci Numarası",
"Ragihandinên Şandî":"Gönderilen Duyurular",
"Sernava ragihandinê...":"Duyuru başlığı...",
"Nivîsa ragihandinê...":"Duyuru metni...",
"Wêne / Dosya Zêde Bike":"Fotoğraf / Dosya Ekle",
"Pêvekirin (vebijarkî)":"Ekler (isteğe bağlı)",
"dosya / wêne":"dosya / fotoğraf",
"Ders hate jêbirin":"Ders silindi",
"Bepejirîn":"Onaylandı",
"Red bû":"Reddedildi",
"✓ Bipejirine":"✓ Onayla",
"✕ Red bike":"✕ Reddet",
"Karên bendewar tune":"Bekleyen iş yok",
"Rêveber Profîlê":"Yönetici Profili",
"📆 Demsal (Dönemler)":"📆 Dönemler",
"Çalak bike":"Aktif yap",
"➕ Demsalê Zêde Bike":"➕ Dönem Ekle",
"Nav (ör. 2026 Bihar)":"Ad (örn. 2026 Bahar)",
"Hîn demsal nehatiye danîn. Ders bê demsal jî dixebitin.":"Henüz dönem tanımlanmadı. Dersler dönemsiz de çalışır.",
"⚠ Nav û tarîx pêwîst in":"⚠ Ad ve tarihler gerekli",
"Hemû demsal":"Tüm dönemler",
"Bê demsal":"Dönemsiz",
"xwendekar derbasî sinifa jorîn bûn":"öğrenci üst sınıfa geçti",
"Demsal girtî: ":"Dönem kapandı:",
"Ders bişimitîne?":"Bu ders silinsin mi?",
"⚠ mamoste nehatiye tayînkirin":"⚠ öğretmen atanmadı",
"Mamoste nehat (îro)":"Öğretmen gelmedi (bugün)",
"⚠ Ev ders îro nîne":"⚠ Bu ders bugün yok",
"Îro mamoste NEHAT — were tomarkirin?":"Bugün öğretmen GELMEDİ — kaydedilsin mi?",
"Hat tomarkirin: mamoste nehat":"Kaydedildi: öğretmen gelmedi",
"Demsalê bigire — sinifan derbas bike":"Dönemi kapat — sınıfları geçir",
"Hemû qad":"Tüm alanlar",
"vala = otomatîk":"boş = otomatik",
"Xwendekarên pejirandî sinifekê derbas dibin (1. → 2.). Yên dubare dikin, îşaretê rake.":"Onaylanan öğrenciler bir üst sınıfa geçer (1. → 2.). Sınıfı tekrar edenlerin işaretini kaldırın.",
"Yên bijartî derbas bike":"Seçilenleri geçir",
"Derbasbûna Sinifê":"Sınıf Geçme",
"Hişyarî":"Uyarılar",
"Hûrgulî →":"Ayrıntı →",
"Hêvîdar →":"Bekleyen →",
"Tomarkirin":"Kaydedildi",
"Tunebûn":"Devamsızlık",
"Rêjeya Amadebûnê":"Devam Oranı",
"Amadebûn %":"Devam %",
"dersê beşdar bû":"derse katıldı",
"tunebû":"devamsız",
"Grafika Hefteyê":"Haftalık Grafik",
"Nirxandina Performansê":"Performans Değerlendirmesi",
"Etîketa Performansê":"Performans Etiketi",
"Nîşeya Mamoste":"Öğretmen Notu",
"Not zêde bike...":"Not ekle...",
"Kêm":"Düşük",
"Navîn":"Orta",
"Baş":"İyi",
"Agahdarî û Hişyarî":"Uyarılar ve Bildirimler",
"Tu hişyarî tune":"Uyarı yok",
"Hemû xwendî bimîne":"Tümünü okundu say",
"Hemû jê bibe":"Tümünü temizle",
"Nirxandina kêm":"Düşük değerlendirme puanı",
"Amadebûna kêm":"Düşük devam",
"Hefte":"Hafta",
"Navgîn":"Ortalama",
"Raporta Nirxandinê":"Değerlendirme Raporu",
"Raporta Demsalê":"Dönem Raporu",
"Raporta Hefteyê":"Haftalık Rapor",
"Hemû Qadan":"Tüm Alanlar",
"Rewşa Amadebûnê":"Devam Durumu",
"Kêm (<50%)":"Düşük (<%50)",
"Navîn (50–79%)":"Orta (%50–79)",
"Baş (≥80%)":"İyi (≥%80)",
"Encamên Nirxandinê":"Değerlendirme Sonuçları",
"Ev hefte bersiv tune":"Bu hafta yanıt yok",
"PDF Dakêşe":"PDF İndir",
"Çap bike":"Yazdır",
"Hişyarî — Xwendekarên Binê %50":"Uyarı — %50'nin Altındaki Öğrenciler",
"Tu xwendekar binê %50 nîne":"%50'nin altında öğrenci yok",
"Roja Rapor":"Rapor Tarihi",
"Rojên yoklamayê":"Aralıktaki yoklama günleri",
"Mamoste nehat":"Öğretmen gelmedi",
"Rojên ku mamoste nehat":"Öğretmenin gelmediği günler",
"Hîn nirx tune":"Henüz puan yok",
"Jm.":"No",
"Rapor hat dakêşandin":"Rapor indirildi",
"Popup hat asteng kirin":"Açılır pencere engellendi",
"Her rapora hatî çêkirin li vir tê tomarkirin (100 yên dawî).":"Oluşturulan her rapor burada kaydedilir (son 100).",
"bersiv":"yanıt",
"Encamên Ankêtê":"Anket Sonuçları",
"Hîn bersiv tune":"Henüz yanıt yok",
"Mohr û Îmze":"Mühür ve İmza",
"Encamên Ankêtê — ":"Anket Sonuçları —",
"Ankêt: ":"Anket:",
"Encamên her ankêta weşandî — wek PDF an CSV bikişîne.":"Yayınlanan her anketin sonuçları — PDF veya CSV olarak alın.",
"Hîn ankêt tune.":"Henüz anket yok.",
"pirs":"soru",
"Lîste":"Listeler",
"Nirxandin":"Değerlendirme",
"Raporu Tevahî ya Xwendekaran":"Tam Öğrenci Raporu",
"Raporu Amadebûnê":"Devam Raporu",
"Cureyê Rapor":"Rapor Türü",
"Rapor Tevahî":"Tam Rapor",
"Burs / Xelat":"Burs / Ödül",
"Rapor hat dakêşîn!":"Rapor indirildi!",
"Raporu Ankêtê":"Anket Raporu",
"Encam li gorî Dersê":"Derse Göre Sonuçlar",
"Hejmar":"Sayı",
"Bersiv tune":"Henüz yanıt yok",
"Li gorî Dersê":"Derse Göre",
"Armanca Ankêtê":"Anket Hedefi",
"Mamosteên Qadê":"Alan Öğretmenleri",
"Li jêr qadekê hilbijêre da ku bi qadê veqetîne":"Alana göre süzmek için aşağıdan bir alan seçin",
"Fîltera Qadê":"Alan Filtresi",
"🏫 Hemû Qadan":"🏫 Tüm Alanlar",
"Kurte":"Özet",
"Navgîna Amadebûnê":"Ortalama Devam",
"Di Xeterê de":"Risk Altında",
"xw.":"öğr.",
"cevap":"yanıt",
"zêdetir (di rapor de hemû hene)":"daha (indirilen raporda hepsi var)",
"Pêşbîna Ankêtê":"Anket Önizlemesi",
"Ji bo vê armancê bersiv tune":"Bu kapsam için anket yanıtı yok",
"Raporu Dakêşe":"Raporu İndir",
"Ankêt Raporu hat dakêşîn":"Anket raporu indirildi",
"Raporu Pêşbinê":"Raporu Önizle",
"⚠ Sernav pêwîst e":"⚠ Başlık gerekli",
"⚠ Herî kêm 1 pirs zêde bike":"⚠ En az 1 soru ekleyin",
"çalak e!":"yayında!",
"Mîheng hate tomarkirin":"Ayarlar kaydedildi",
"👨‍🏫 Mamoste Ankêtê":"👨‍🏫 Öğretmen Anketleri",
"🎓 Xwendekar Ankêtê":"🎓 Öğrenci Anketleri",
"Pirsên Ankêtê":"Anket Soruları",
"Hîn encam tune":"Henüz sonuç yok",
"Hûrgulî":"Ayrıntılar",
"Ankêta Nû Biafirîne":"Yeni Anket Oluştur",
"Ankêtên Hazir":"Hazır Anketler",
"Sernava Ankêtê":"Anket Başlığı",
"Danasîn (vebijarkî)":"Açıklama (isteğe bağlı)",
"Kî Beşdar Dibe?":"Kimler katılacak?",
"Qadên Bijartî":"Seçili Alanlar",
"Pirsê Zêde Bike":"Soru Ekle",
"Nivîsa Pirsê":"Soru metni",
"Cureya Pirsê":"Soru türü",
"Pûan (1-10)":"Puan (1-10)",
"Nivîs Azad":"Serbest metin cevabı",
"Çend Vebijark":"Çoktan seçmeli",
"Vebijark":"Seçenekler",
"Çalak Bike":"Etkinleştir",
"Rawestîne":"Durdur",
"✅ Çalak":"✅ Aktif",
"⏸ Neçalak":"⏸ Pasif",
"Encaman Bibîne":"Sonuçları Gör",
"Hîn ankêt nehatiye çêkirin":"Henüz anket oluşturulmadı",
"Agahî":"Bilgi",
"Encam Cureyê":"Sonuç Türü",
"Pirsên":"Sorular",
"Pêştir →":"İleri →",
"Rêjeya % (yüzdelik)":"Yüzde %",
"Pûan (puan sistemi)":"Puan sistemi",
"Sual – Cewab":"Soru – Cevap (metin yanıtları)",
"Tevlihev (hemû)":"Karışık (tüm türler)",
"Belge an wêne piştgirî?":"Belge/görsel yüklenebilsin mi?",
"Pirsê hate zêdekirin":"Soru eklendi",
"Herî kêm 1 pirsek lazim e":"En az 1 soru gerekli",
"Hate jêbirin":"Silindi",
"Rêjeya %":"Yüzde",
"Her pirsê ji 100'ê tê nirxandin û encam wekî % nîşan tê dan":"Her soru 100 üzerinden değerlendirilir, sonuç yüzde olarak gösterilir",
"Pûan Sistemi":"Puan Sistemi",
"Her pirsê xalên xwe hene, encam wekî pûan hatiye berhevkirin":"Her sorunun puanı vardır, sonuçlar puan olarak toplanır",
"Xwendekarên bersivên nivîskî didin, encam wekî nivîs tê berhevkirin":"Öğrenciler yazılı cevap verir, sonuçlar metin olarak toplanır",
"Tevlihev":"Karışık Türler",
"Pûan, rêje û nivîs bi hev re dikarin bibin ankêtê":"Puan, yüzde ve metin soruları bir arada",
"Ankêt Mîhengên":"Anket Ayarları",
"Mamoste ankêtê çalak / neçalak bike":"Öğretmen anketini etkinleştir / durdur",
"Nirxandina dersê":"Ders değerlendirmesi",
"Encamên":"Sonuçlar",
"Ev pirs ji aliyê MAMOSTEYAN ve, di nirxandina dersê ya hefteyî de tên bersivdan. Ji bo ankêta xwendekaran, sêrbazê ankêtê yê jêrîn bikar bîne.":"Bu soruları ÖĞRETMENLER haftalık ders değerlendirmesinde yanıtlar. Öğrencilere anket hazırlamak için aşağıdaki anket sihirbazını kullanın.",
"Pirsa Nû Zêde Bike":"Yeni Soru Ekle",
"Ankêta Agahî":"Anket Bilgisi",
"Sernav û danasîna ankêtê binivîse":"Anket başlığını ve açıklamasını yazın",
"Mînak: Ders Nirxandina Mehane":"Örn. Aylık ders memnuniyeti anketi",
"Danasînek kurt ji bo xwendekaran...":"Öğrenciler için kısa bir açıklama...",
"Bu ankêtê kê tije bikin?":"Bu anketi kimler dolduracak?",
"Akademiya hemû xwendekarên":"Akademinin tüm öğrencileri",
"Tenê qadên bijartî":"Yalnızca seçili alanlar",
"Akademiya hemû mamosteyên":"Akademinin tüm öğretmenleri",
"Mamoste (Qad)":"Öğretmenler (Alan)",
"Tenê qadên bijartî mamosteyên":"Yalnızca seçili alanların öğretmenleri",
"Qadan hilbijêre":"Alanları seçin",
"Herî kêm 1 qad hilbijêre":"En az 1 alan seçin",
"Encamên ankêtê çawa nîşan bide?":"Anket sonuçları nasıl gösterilsin?",
"Her pirsê max pûan":"Soru başına en yüksek puan",
"Pirsên Hatine Zêdekirin":"Eklenen Sorular",
"Pûan":"Puan",
"Pirsa xwe binivîse...":"Sorunuzu yazın...",
"Vê pirsê pûan":"Bu sorunun puanı",
"Zêde bike":"Seçenek ekle",
"Belge & Wêne":"Belge ve Görsel",
"Xwendekarên dikarin wêne an belge bar bikin?":"Öğrenciler belge veya görsel yükleyebilsin mi?",
"Na, tenê pirsên":"Hayır, yalnızca sorular",
"Erê, xwendekar dikare dosya bar bike":"Evet, öğrenci dosya yükleyebilir",
"Şablona Belgeyê (vebijarkî)":"Belge şablonu (isteğe bağlı)",
"Xwendekarên dixwazin tije bikin û bar bikin — ev belge wekî nimûne an şablona tê şandin":"Öğrenciler indirir, doldurur ve yükler — bu, onlara gönderilen şablon dosyadır",
"Belge bar bike (PDF, Word...)":"Şablon yükle (PDF, Word...)",
"Kurtasiya Ankêtê":"Anket Özeti",
"👨‍🏫 Hemû Mamoste":"👨‍🏫 Tüm Öğretmenler",
"Pirsên Hejmara":"Soru Sayısı",
"Nayê destûrkirin":"İzin yok",
"Destûr heye":"İzin var",
"Ankêtê Tomar Bike":"Anketi Kaydet",
"Yekem ankêta xwe biafirîne":"İlk anketinizi oluşturun",
"Rêveberiya Ankêtan":"Anket Yönetimi",
"Ankêta Nû":"Yeni Anket",
"Bilez Ankêt":"Hızlı Anket",
"Sernav + pirs — tavilê çalak dibe. Ji bo vebijarkên pêşketî sêrbazê bikar bîne.":"Başlık + sorular — hemen yayına girer. Gelişmiş seçenekler için aşağıdaki sihirbazı kullanın.",
"Sernava ankêtê":"Anket başlığı",
"Pirs ":"Soru",
"Pirs":"Soru",
"Biafirîne û Çalak Bike":"Oluştur ve Yayınla",
"📥 Gihîştî":"📥 Gelen",
"📤 Bişîne":"📤 Gönder",
"📋 Şandî":"📋 Gönderilen",
"Ragihandin tune":"Duyuru yok",
"Ragihandin tenê bo xwendekarên {0} tê şandin.":"Bu duyuru yalnızca {0} öğrencilerine gönderilecek.",
"Hîn ragihandin nehatiye şandin":"Henüz duyuru gönderilmedi",
"Niha ji bo qada te ankêt tune.":"Şu an bölümünüz için aktif anket yok.",
"Nirxandina Hefteyê":"Haftalık Değerlendirme",
"✓ Nirxandin hate şandin":"✓ Değerlendirme gönderildi",
"Nûve bike":"Güncelle",
"Ji %0 heya %100 — sirbike":"%0–100 arası kaydırın",
"Bernameya ders tune":"Programda ders yok",
"Hîn pirsên ankêtê nehatine destnîşankirin":"Henüz anket sorusu tanımlanmadı",
"Herî kêm 1 pirsa bersivê bide":"Lütfen en az 1 soruyu puanlayın",
"Herî kêm 1 bersivê bide":"En az 1 soruyu yanıtlayın",
"Ankêt hate şandin":"Anket gönderildi",
"Ankêtên ji Rêveber":"Yönetimden Gelen Anketler",
"Bersiva nayê dan — bikirtîne":"Bekliyor — doldurmak için dokunun",
"Bersiv hatiye dan ✓":"Yanıtlandı ✓",
"Bersiva te hatiye tomarkirin":"Yanıtınız kaydedildi",
"Bersiva xwe binivîse...":"Cevabınızı yazın...",
"Belge / Wêne (vebijarkî)":"Belge / Fotoğraf (isteğe bağlı)",
"Pel barkirin":"Dosya yükle",
"Xirab":"Kötü",
"Bêkêmasî":"Mükemmel",
"Agahiyên Kesane":"Kişisel Bilgiler",
"Roja Jidayikbûnê":"Doğum Tarihi",
"Derbarê":"Hakkında",
"Mîhengên Hesabê":"Hesap Ayarları",
"Profîla Min":"Profilim",
"Şîfre Biguherîne":"Şifre Değiştir",
"Hesabê Min Jê Bibe":"Hesabımı Sil",
"📅 Bername":"📅 Programlı",
"🟢 Niha çalak":"🟢 Şu an aktif",
"⏰ {0}{1}d sonra":"⏰ {0}{1}dk sonra",
"✓ Biqedî":"✓ Tamamlandı",
"Ders tenê di roj û saeta xwe de dest pê dike":"Ders yalnızca planlanan gün ve saatte başlatılabilir",
"Te ev QR çap kiribû. Eger nû bikî, kaxeza ÇAPKIRÎ betal dibe — xwendekar nikarin wê bixwînin.\n\nBerdewam bike û ya nû çap bike?":"Bu QR'ı yazdırmıştınız. Yenilerseniz YAZDIRILAN kâğıt geçersiz olur — öğrenciler onu okutamaz.\n\nDevam edip yeni QR yazdırılsın mı?",
"🔄 QR ya nû hat çêkirin — ya kevn betal bû":"🔄 Yeni QR oluşturuldu — eskisi artık geçersiz",
"kete dersê":"derse girdi",
"Ankêta Hefteyê Çalak e!":"Haftalık Anket Aktif!",
"Nirxandina xwe bide":"Değerlendirmeni gönder",
"Îro bername tune":"Bugün program yok",
"ragihandina nû":"yeni duyuru",
"Vê agahiyê tenê rêveber dibîne":"Bu bilgiyi yalnızca yönetici görür",
"Ji bo agahiyên bêtir ji rêveberê xwe bipirsin":"Daha fazla bilgi için yöneticinize başvurun",
"Îro ders tune":"Bugün ders yok",
"Amadebûn tenê di roja dersê de tê girtin.":"Yoklama yalnızca ders günü alınabilir.",
"Materyalên Dersê":"Ders Materyalleri",
"Ji bo xwendekarên xwe materyalên dersê barkirin.":"Öğrencileriniz için ders materyali yükleyin.",
"Pelê Barkirin":"Dosya Yükle",
"Materyala Nû":"Yeni Materyal",
"Pel":"Dosyalar",
"Hîn materyaleke nehatiye barkirin":"Henüz materyal yüklenmedi",
"Dersa QR":"QR için Ders Seçin",
"Hefteyê":"Bu Hafta",
"QR Oturumê Veke":"QR Oturumu Başlat",
"Xwendekar QR-ê bi têlefonê skane dikin û dersê dikevê":"Öğrenciler telefonla QR'ı okutarak derse girer",
"QR ya Dersê Veke":"Ders QR'ını Aç",
"Oturum Çalak e":"Oturum Aktif",
"Ketin":"Giriş yaptı",
"Çap":"Yazdır",
"Ketinên Dawî":"Son Girişler",
"Dersên Derbasbûyî":"Geçmiş Dersler",
"Hemû Xwendekaran Peyam Bişîne":"Tüm Öğrencilere Mesaj Gönder",
"Peyama Girseyî":"Toplu Mesaj",
"Hîn xwendekar tune":"Henüz öğrenci yok",
"🔒 Şîfre Biguherîne":"🔒 Şifre Değiştir",
"Şîfreya Niha":"Mevcut Şifre",
"Şîfreya Nû (Dubare)":"Yeni Şifre (Tekrar)",
"Hemû qadan dagire":"Tüm alanları doldurun",
"Herî kêm 8 tîp, tîpa mezin û hejmar lazim e":"En az 8 karakter, büyük harf ve rakam gerekli",
"Şîfreyên nû li hev nayên":"Şifreler eşleşmiyor",
"Şîfreya niha xelet e":"Mevcut şifre yanlış",
"Şîfre Tomar Bike":"Şifreyi Kaydet",
"Naha dikari bi şîfreya nû têkevi.":"Artık yeni şifrenizle giriş yapabilirsiniz.",
"Şîfre: herî kêm 8 tîp, 1 tîpa mezin, 1 hejmar":"Şifre: en az 8 karakter, 1 büyük harf, 1 rakam",
"⚠ Şîfre binivîse":"⚠ Şifrenizi girin",
"⚠ Şîfre xelet e":"⚠ Şifre yanlış",
"Ewlekariya Dersê":"Ders Güvenliği",
"Ji bo ketin dersê, nasnameya xwe piştrast bike":"Derse girmek için kimliğinizi doğrulayın",
"Tiliya Destê / Rûnasîn":"Parmak İzi / Yüz Tanıma",
"Şîfreya Hesabê Binivîse":"Hesap Şifrenizi Girin",
"Şîfreya ku bi têketinê bikar tîni binivîse":"Giriş yaparken kullandığınız şifreyi girin",
"Piştrast Bike":"Onayla",
"Şîfreya Hesabê Bikar Bîne":"Hesap Şifresini Kullan",
"✓ Nasname piştrast bû!":"✓ Kimlik doğrulandı!",
"Şaşitî çêbû. Ji nû ve biceribîne.":"Doğrulama başarısız. Tekrar deneyin.",
"Hûn dikarin dersê bikevin...":"Derse giriliyor...",
"Ankêt hate şandin!":"Anket gönderildi!",
"Ankêta te hat tomarkirin. Spas!":"Yanıtınız kaydedildi. Teşekkürler!",
"Pûanê xwe hilbijêre (1=xirab, 10=bêkêmasî)":"Puan seçin (1=kötü, 10=mükemmel)",
"Ankêtê Bişîne":"Anketi Gönder",
"Ankêtên Çalak":"Aktif Anketler",
"Rêveberê akademiyê yên li jêr bersiv bide.":"Lütfen akademinin gönderdiği aşağıdaki anketleri doldurun.",
"Beşdar bibe":"Katıl",
"Bersivand":"Yanıtlandı",
"pirsên":"soru",
"Bersivandî":"Gönderildi",
"Niha ti ankêta çalak tune.":"Şu an aktif anket yok.",
"💡 Pêşniyar û Gilî":"💡 Öneri ve Şikâyetler",
"💡 Pêşniyar":"💡 Öneri",
"⚠️ Gilî":"⚠️ Şikâyet",
"❓ Pirsek":"❓ Soru",
"Sernavê Peyamê":"Mesaj Konusu",
"Peyama Te":"Mesajınız",
"Nenas bişîne (nav nayê xuyang kirin)":"İsimsiz gönder (ad gizlenir)",
"✅ Peyama te hat şandin! Rêveber dê bersivê bide.":"✅ Mesajınız gönderildi! Yönetici yanıtlayacak.",
"Sernav û peyamê dagire":"Konu ve mesajı doldurun",
"Peyamên Berê":"Önceki Mesajlar",
"Hîn pêşniyar nehatiye şandin":"Henüz öneri gönderilmedi",
"Peyamên te rasterast li qutiya peyaman ya rêveber dikeve.":"Mesajlarınız doğrudan yöneticinin mesaj kutusuna gider.",
"Nenas":"İsimsiz",
"Peyama te hat şandin":"Mesajınız gönderildi!",
"Cureyê Peyamê":"Mesaj Türü",
"Rasterast li admin tê şandin":"Doğrudan yöneticiye gönderilir",
"Peyama xwe binivîse...":"Mesajınızı yazın...",
"Têketina Dersê":"Derse Giriş",
"Pêşniyar":"Öneri",
"Niha çalak":"Şu an aktif",
"Hemûyan bibîne →":"Tümünü gör →",
"Koda QR ya mamosteyê bixwîne da amadebûna xwe rastbike.":"Devamınızı onaylamak için öğretmenin QR kodunu okutun.",
"Rûniştina Dersa Çalak":"Aktif Ders Oturumu",
"Hîn rûniştina çalak tune":"Henüz aktif ders oturumu yok",
"Gava mamoste QR veke, agahdarî tê":"Öğretmen QR'ı açtığında bildirim alacaksınız",
"Koda QR Bixwîne":"QR Kodu Okut",
"Koda QR ya Nasnameyê":"Kimlik QR Kodu",
"Hemûyan xwendî nîşan bide":"Tümünü okundu işaretle",
"Peyamên Min":"Mesajlarım",
"ders · Bernameya hefteyê":"ders · Haftalık program",
"Hîn ders nehatiye zêdekirin":"Henüz ders eklenmedi",
"Agahiyên Qadê":"Alan Bilgisi",
"Karta Nasnameyê":"Öğrenci Kimlik Kartı",
"Nasname piştrast bû, dersê bikeve!":"Kimlik doğrulandı — derse giriliyor!",
"Hesab {0} deqe kilî ye":"Hesap {0} dakika kilitli",
"⚠ Hesabê Firebase bi şîfreya nû re ne wek hev e. Rêveber: Firebase Console → Authentication → vî hesabî jê bibe; di têketina pêş de bixweber ji nû ve tê çêkirin.":"⚠ Firebase hesabı yeni şifreyle eşleşmiyor. Yönetici: Firebase Console → Authentication'da bu hesabı silin; bir sonraki girişte otomatik yeniden oluşturulur.",
"Hesab kilî ye":"Hesap kilitli",
"🔒 Ev hesab li cîhazekî din tomar bûye. Ji rêveber re vebêje ku cîhazê sıfırla bike.":"🔒 Bu hesap başka bir cihazda kayıtlı. Cihazınızın sıfırlanması için yöneticiye başvurun.",
"Kamera nehat dîtin":"Kamera bulunamadı",
"Xwendekar nehat dîtin: ":"Öğrenci bulunamadı:",
"Dersa aktîf nîne":"Aktif ders yok",
"Berê ketibû: ":"Zaten girdi:",
"Karta xwendekarê bixwîne":"Öğrenci kimlik kartındaki QR'a tutun",
"Ketine Dersê":"Derse Girdi",
"Karta Xwendekarê Bixwîne":"Öğrenci Kartını Okut",
"Kaxeza QR Çap Bike":"QR Sayfasını Yazdır",
"QR ya Nû":"Yeni QR",
"Koda QR ya mamosteyê bixwîne":"Öğretmenin QR kodunu okutun",
"Koda bi destan binivîse":"Kodu elle girin",
"Dîsa biceribîne":"Tekrar dene",
"Wêne bigire & bixwîne":"Fotoğraf çek ve okut",
"Kamera tê destpêkirin…":"Kamera başlatılıyor…",
"Vegere kamerayê":"Kameraya dön",
"Baş e":"Tamam",
"Têketin Hate Pejirandin!":"Giriş Onaylandı!",
"Têketin Pêk Nehat":"Giriş Başarısız",
"Civîna dersê ya çalak nehat dîtin.":"Aktif ders oturumu bulunamadı.",
"Civîna dersê hatiye girtin.":"Ders oturumu kapatıldı.",
"Dema QR ya dersê derbas bûye.":"Ders QR'ının süresi doldu.",
"Koda QR ya şaş an dem bûye.":"Geçersiz veya süresi dolmuş QR kodu.",
"Berê ketina vê dersê qeyd kir.":"Bu derse zaten giriş yaptınız.",
"📍 Tu ji dersê re dûr î — nêziktir bibe.":"📍 Derse çok uzaksınız — yaklaşın.",
"📍 Ji bo têketinê cih lazim e — GPS-ê veke.":"📍 Giriş için konum gerekli — lütfen GPS'i açın.",
"🚫 Tu ne xwendekarê vê dersê yî.":"🚫 Bu derse kayıtlı değilsiniz.",
"Koda QR nehat dîtin — dîsa biceribîne":"QR kodu bulunamadı — tekrar deneyin",
"Mamoste QR-ê veke":"Aktif QR yok — öğretmenden açmasını isteyin",
"Dem derbas bûye":"Süre doldu",
"Koda QR xelet e":"Yanlış QR kodu",
"Berê ketibûye ✓":"Zaten giriş yapıldı ✓",
"Tu ne xwendekarê vê dersê yî":"Bu derse kayıtlı değilsiniz",
"Xelet":"Hata",
"Ji bo wênegirtina koda QR li ser îkona kamerayê bitikîne":"QR kodun fotoğrafını çekmek için kamera simgesine dokunun",
"Koda rûniştinê ya li ser ekrana mamosteyê binivîse":"Öğretmenin ekranındaki oturum kodunu girin",
"📍 Cih tê verastkirin...":"📍 Konum doğrulanıyor...",
"📲 Malpera Serê Zêde Bike":"📲 Ana Ekrana Ekle",
"Wek sepekê dixebite, offline piştgirî":"Uygulama gibi çalışır, çevrimdışı destekli",
"Zêde Bike":"Yükle",
"Paşê":"Sonra",
"Temaya Tarî":"Koyu tema",
"Temaya Ronahî":"Açık tema",
"✓ Agahdarî çalak e – Ji mîhengên geroka neçalak bike":"✓ Bildirimler zaten açık – kapatmak için tarayıcı ayarlarını kullanın",
"📲 Geroka veke → Parve bike → Li ekranê zêde bike":"📲 Tarayıcıda aç → Paylaş → Ana Ekrana Ekle",
"✓ Sepet berê hatiye sazkirin":"✓ Uygulama zaten yüklü",
"✓ Sepet hate sazkirin!":"✓ Uygulama yüklendi!",
"Ziman":"Dil",
"Moda Ronahî":"Açık Mod",
"Moda Tarî":"Koyu Mod",
"Temaya xuyangê biguherîne":"Görünüm temasını değiştir",
"Agahdarî":"Bildirimler",
"Bikirtînin ji bo çalakkirinê":"Açmak için dokunun",
"Di geroka bûye asteng":"Tarayıcıda engellendi",
"Çalak e":"Açık",
"Sazkirina Sepetê":"Uygulamayı Yükle",
"Li ekrana serê zêde bike (offline destekli)":"Ana ekrana ekle (çevrimdışı destekli)",
"Çawa daneyên we têne parastin":"Verileriniz nasıl korunuyor",
"Bikaranîna sepetê":"Kullanım kuralları ve koşullar",
"v4.0 de çi nû ye":"v4.0'daki yenilikler",
"Danişîn qediya — ji nû ve têkeve":"Oturum süresi doldu — tekrar giriş yapın",
"❌ Xelet: ":"❌ Kaydedilemedi:",
"Ji vê jimarê re hesabekî Firebase yê kevn heye ({0}). Di Console → Authentication de jê bibe, paşê dîsa zêde bike.":"Bu numaraya ait eski bir Firebase hesabı var ({0}). Console → Authentication'da silin, sonra tekrar ekleyin.",
"❌ Tomarkirina serneket":"❌ Kaydedilemedi, bağlantıyı kontrol edin",
"❌ Nûvekirina serneket":"❌ Güncellenemedi",
"Hesabê Auth nehat jêbirin — di Firebase Console de {0} jê bibe":"Auth hesabı silinemedi — Firebase Console'da {0} hesabını silin",
"⚠ Tenê lokalî hate jêbirin — Firebase ID tune":"⚠ Öğrenci yalnızca yerelde silindi (Firebase ID yok)",
"❌ Jêbirin serneket — girêdan kontrol bike":"❌ Silinemedi — bağlantıyı kontrol edin",
"Şîfreya nû (min 6 tîp)":"Yeni şifre (en az 6 karakter)",
"⚠ Şîfre divê herî kêm 6 tîp be":"⚠ Şifre en az 6 karakter olmalı",
"Dêûbav? Têketina Akademiya Zarokan →":"Veli misiniz? Çocuk Akademisi uygulamasına giriş →",
"Ev serlêdan were jêbirin?":"Bu başvuru silinsin mi?",
"Tomara zarokê were jêbirin?":"Çocuğun kaydı silinsin mi?",
"⚠ Ji bo vê yekê Cloud Functions pêwîst e (FUNCTIONS.md)":"⚠ Bunun için Cloud Functions gerekli (FUNCTIONS.md)",
"⚠ Navê dersê pêwîst e":"⚠ Ders adı gerekli",
"⚠ Sernav û nivîs pêwîst in":"⚠ Başlık ve metin gerekli",
"✅ Ji dêûbavan re hat şandin":"✅ Velilere gönderildi",
"Zarok û Dêûbav":"Çocuklar ve Veliler",
"Firebase girêdayî nîne.":"Firebase bağlı değil.",
"Akademiya Zarokan":"Çocuk Akademisi",
"Tenê dêûbav têketin dikin · sepan:":"Yalnızca veliler giriş yapar · uygulama:",
"Şîfreya nû":"Yeni şifre",
"Zarok hate tomarkirin":"Çocuk kaydedildi",
"Jimara zarokê":"Çocuk no",
"Dêûbav":"Veli",
"Jimara têketinê":"Giriş no",
"Dêûbav berê hesab heye — zarok li hesabê wî/wê hat zêdekirin.":"Velinin zaten hesabı var — çocuk bu hesaba eklendi.",
"Van agahiyan bide dêûbav. Têketin: ":"Bu bilgileri veliye verin. Giriş adresi: ",
"✉ Agahiyên têketinê bi e-peyamê çûn.":"✉ Giriş bilgileri e-postayla gönderildi.",
"🔴 Serlêdana zarokan GIRTÎ ye":"🔴 Çocuk başvuruları KAPALI",
"🟢 Serlêdana zarokan VEKIRÎ ye":"🟢 Çocuk başvuruları AÇIK",
"Veke":"Aç",
"Têkiliya acil":"Acil durum kişisi",
"wêne":"fotoğraf",
"parvekirin":"paylaşım",
"zarok":"çocuk",
"dêûbav":"veli",
"Hîn zarok nehatiye tomarkirin.":"Henüz çocuk kaydı yok.",
"Dikarin zarokê bibin":"Çocuğu alabilir",
"Dêûbav di cih de agahdar dibin":"Veliler anında bilgilendirilir",
"hîn nehatiye":"henüz gelmedi",
"Hate teslîmkirin":"Teslim edildi",
"Di dersê de":"Derste",
"Hat":"Geldi",
"Çû":"Çıktı",
"Navê dersê (mînak: Muzîka Zarokan)":"Ders adı (örn. Çocuk Müziği)",
"Ode":"Sınıf",
"Dersê Zêde Bike":"Ders Ekle",
"Ji bo dêûbavan nivîs…":"Velilere mesaj…",
"Ji Dêûbavan re Bişîne":"Velilere Gönder",
"Hîn peyam tune.":"Henüz mesaj yok.",
"Bersiv binivîse…":"Yanıt yazın…",
"⚠ Navê zarokê pêwîst e":"⚠ Çocuğun adı gerekli",
"⚠ Navê dêûbav û têlefon pêwîst in":"⚠ Veli adı ve telefon gerekli",
"Şîfreyeke nû were çêkirin?":"Yeni şifre oluşturulsun mu?",
"⚠ Şîfre nehat guhertin — Cloud Functions veke (FUNCTIONS.md)":"⚠ Şifre değiştirilemedi — Cloud Functions açın (FUNCTIONS.md)",
"⚠ Pêşî zarokên girêdayî jê bibe":"⚠ Önce bağlı çocukları kaldırın",
"Hesabê dêûbav were jêbirin?":"Veli hesabı silinsin mi?",
"Mamoste were jêbirin?":"Öğretmen silinsin mi?",
"⚠ Sal pêwîst e (mînak 2019)":"⚠ Yıl gerekli (örn. 2019)",
"✅ Hate weşandin":"✅ Yayınlandı",
"➕ Nûçeya nû":"➕ Yeni haber",
"➕ Tomara arşîvê":"➕ Arşiv kaydı",
"✏️ Biguherîne":"✏️ Düzenle",
"Etîket":"Etiket",
"mînak: Damezrandin":"örn. Kuruluş",
"Dîrok":"Tarih",
"📷 Wêne (herî zêde 4)":"📷 Fotoğraflar (en fazla 4)",
"Wêne":"Fotoğraf",
"Biweşîne":"Yayınla",
"Betal":"İptal",
"Were jêbirin?":"Silinsin mi?",
"Zarok":"Çocuklar",
"Têketin":"Giriş",
"Têketin: dêûbav û mamoste · sepan:":"Giriş: veliler ve öğretmenler · uygulama:",
"malper":"site",
"Van agahiyan bide xwedîyê hesabê.":"Bu bilgileri hesap sahibine verin.",
"Parve bike":"Paylaş",
"Zarokê Tescîl Bike":"Çocuk Kaydet",
"➕ Zarokê nû":"➕ Yeni çocuk",
"✏️ Zarok biguherîne":"✏️ Çocuğu düzenle",
"Nav û paşnavê zarokê *":"Çocuğun adı soyadı *",
"Dibistan / sinif":"Okul / sınıf",
"Nîşeya tenduristiyê":"Sağlık notu",
"Destûra wêneyan":"Fotoğraf izni",
"Destûra parvekirinê li malperê":"Sitede paylaşım izni",
"Hesabê nû":"Yeni hesap",
"Dêûbavê heyî":"Mevcut veli",
"Navê dêûbav *":"Veli adı *",
"Yekîtî (dayik, bav…)":"Yakınlık (anne, baba…)",
"Têlefon *":"Telefon *",
"E-peyam (agahiyên têketinê)":"E-posta (giriş bilgileri)",
"Şîfre otomatîk tê çêkirin û bi e-peyamê tê şandin.":"Şifre otomatik oluşturulur ve e-postayla gönderilir.",
"Kesên ku dikarin zarokê bibin (her rêzek yek)":"Çocuğu alabilecek kişiler (her satıra bir kişi)",
"Dêûbavekî din girê bide":"Başka bir veli bağla",
"Dêûbav biguherîne":"Veliyi düzenle",
"Nav":"Ad",
"Yekîtî":"Yakınlık",
"E-peyam":"E-posta",
"Dêûbav bi tomarkirina zarokê re tê çêkirin.":"Veli hesapları çocuk kaydı sırasında oluşturulur.",
"Mamosteyên zarokan tenê sepana zarokan dibînin.":"Çocuk öğretmenleri yalnızca çocuk uygulamasını görür.",
"Mamoste biguherîne":"Öğretmeni düzenle",
"Nav û paşnav *":"Ad soyad *",
"Jimare û şîfre otomatîk tên çêkirin û bi e-peyamê tên şandin.":"Numara ve şifre otomatik oluşturulur ve e-postayla gönderilir.",
"Hîn mamoste tune.":"Henüz öğretmen yok.",
"ders":"ders",
"Ev nûçe li ser malpera Akademiya Zarokan ji her kesî re xuya dibin.":"Bu haberler Çocuk Akademisi sitesinde herkese açık görünür.",
"Nûçeya nû":"Yeni haber",
"Hîn nûçe tune.":"Henüz haber yok.",
"Tomarên «Dîroka Akademiyê» ya malpera zarokan (bi salan). Nûçeyên weşandî jî bixweber tên zêdekirin.":"Çocuk sitesindeki «Akademinin Tarihi» kayıtları (yıllara göre). Yayınlanan haberler de otomatik eklenir.",
"Tomara arşîvê":"Arşiv kaydı",
"Hîn tomar tune.":"Henüz kayıt yok."}};
window.AAT_SITE={"ku":{},"zza":{}};
window.AAT_SITE_AREA={"ku":{},"zza":{}};
window.AAT_ZAROK={"ku":{},"zza":{}};
window.AAT_ZAROK_SITE={"ku":{},"zza":{}};
