// Güvenlik kuralı testleri (Firestore + Storage emülatörü). Çalıştırma:
//   cd tools && npm install && npm run kural-testi     (Java 11+ gerekir)
const fs = require('fs');
const { initializeTestEnvironment, assertSucceeds, assertFails } = require('@firebase/rules-unit-testing');
const { doc, getDoc, setDoc, updateDoc, deleteDoc, collection, getDocs, query, where, addDoc } = require('firebase/firestore');
const { ref, uploadString, getBytes } = require('firebase/storage');

(async () => {
  const env = await initializeTestEnvironment({
    projectId: 'aram2026-test',
    firestore: { rules: fs.readFileSync(require('path').join(__dirname,'..','firestore.rules'), 'utf8'), host: '127.0.0.1', port: 8080 },
    storage: { rules: fs.readFileSync(require('path').join(__dirname,'..','storage.rules'), 'utf8'), host: '127.0.0.1', port: 9199 },
  });
  await env.withSecurityRulesDisabled(async c => {
    const db = c.firestore();
    await setDoc(doc(db, 'idx_staff/1000'), { no: '1000', lvl: 'admin' });
    await setDoc(doc(db, 'idx_staff/11202601'), { no: '11202601', lvl: 'teacher' });
    await setDoc(doc(db, 'idx_students/10202601'), { no: '10202601' });
    await setDoc(doc(db, 'idx_students/10202602'), { no: '10202602' });
    await setDoc(doc(db, 'teachers/T1'), { no: '1000', name: 'Admin', isAdmin: true });
    await setDoc(doc(db, 'teachers/T2'), { no: '11202601', name: 'Mamoste', phone: '1' });
    await setDoc(doc(db, 'students/S1'), { no: '10202601', name: 'Xwendekar', area: 'sinema', phone: '1' });
    await setDoc(doc(db, 'students/S2'), { no: '10202602', name: 'Din', area: 'muzik' });
    await setDoc(doc(db, 'messages/M1'), { text: 'x' });
    await setDoc(doc(db, 'config/applications'), { open: true });
    await setDoc(doc(db, 'news/N1'), { title: 't' });
    // Zarok
    await setDoc(doc(db, 'idx_guardians/92026001'), { no: '92026001' });
    await setDoc(doc(db, 'idx_guardians/92026002'), { no: '92026002' });
    await setDoc(doc(db, 'guardians/92026001'), { no: '92026001', name: 'Veli A' });
    await setDoc(doc(db, 'kids/K1'), { no: '82026001', name: 'Zarok A', guardianNos: ['92026001'], health: '' });
    await setDoc(doc(db, 'kids/K2'), { no: '82026002', name: 'Zarok B', guardianNos: ['92026002'] });
    await setDoc(doc(db, 'kidAttendance/A1'), { kidId: 'K1', guardianNos: ['92026001'], type: 'in' });
    await setDoc(doc(db, 'kidAttendance/A2'), { kidId: 'K2', guardianNos: ['92026002'], type: 'in' });
    await setDoc(doc(db, 'kidMessages/M1'), { guardianNo: '92026002', text: 'x', from: 'guardian' });
    await setDoc(doc(db, 'config/zarok'), { open: true });
    await setDoc(doc(db, 'idx_kidstaff/72026001'), { no: '72026001' });
    await setDoc(doc(db, 'kidTeachers/72026001'), { no: '72026001', name: 'Mamoste Hêvî' });
    await setDoc(doc(db, 'kidNews/KN1'), { title: 'Nûçe' });
    // v5 rol ayrımı
    await setDoc(doc(db, 'idx_staff/99202601'), { no: '99202601', lvl: 'press' });
    await setDoc(doc(db, 'idx_staff/98202601'), { no: '98202601', lvl: 'registrar' });
    await setDoc(doc(db, 'idx_staff/21202601'), { no: '21202601', lvl: 'teacher' });
    await setDoc(doc(db, 'idx_kidstaff/21202601'), { no: '21202601' });
    await setDoc(doc(db, 'teachers/TP'), { no: '99202601', name: 'Basın', isPress: true });
    await setDoc(doc(db, 'messages/M2'), { recipientNo: '10202601', subject: 'özel' });
    await setDoc(doc(db, 'messages/M3'), { recipientNo: '10202602', subject: 'başkasına özel' });
    await setDoc(doc(db, 'messages/M4'), { recipientGroup: 'allStudents', recipientNo: null, subject: 'toplu' });
    await setDoc(doc(db, 'messages/M5'), { recipientGroup: 'allTeachers', recipientNo: null, subject: 'öğretmenlere' });
    await setDoc(doc(db, 'studentSurveyResponses/R2'), { studentNo: '10202602', answers: {} });
    await setDoc(doc(db, 'applications/AP1'), { name: 'Başvuran', phone: '1', status: 'new' });
    await setDoc(doc(db, 'devices/10202602'), { no: '10202602' });
    // Kartlar + kapı güvenliği
    await setDoc(doc(db, 'idx_staff/97202601'), { no: '97202601', lvl: 'gate' });
    await setDoc(doc(db, 'teachers/TG'), { no: '97202601', name: 'Ewlehî', isGate: true });
    await setDoc(doc(db, 'cards/' + 'a'.repeat(32)), { kind: 'student', no: '10202601', ref: 'S1', name: 'Xwendekar', active: true });
    await setDoc(doc(db, 'cards/' + 'b'.repeat(32)), { kind: 'kid', no: '82026001', ref: 'K1', name: 'Zarok A', active: true });
    await setDoc(doc(db, 'cards/' + 'c'.repeat(32)), { kind: 'student', no: '10202602', ref: 'S2', name: 'Din', active: false });
    await setDoc(doc(db, 'gateLog/G1'), { by: '11202601', ok: true, date: '2026-09-27' });
  });
  const as = e => env.authenticatedContext('uid-' + e, { email: e }).firestore();
  const admin = as('1000@ogretmen.aat'), teacher = as('11202601@ogretmen.aat'), student = as('10202601@ogrenci.aat');
  const fakeStaff = as('9999@ogretmen.aat'), fakeStu = as('7777@ogrenci.aat'), anon = env.unauthenticatedContext().firestore();
  const results = [];
  async function t(name, p, ok) {
    try { await (ok ? assertSucceeds(p) : assertFails(p)); results.push('✅ ' + name); }
    catch (e) { results.push('❌ ' + name + ' — ' + (e.message || e).slice(0, 120)); }
  }
  // Sahte hesaplar
  await t('Sahte personel öğrencileri OKUYAMAZ', getDocs(collection(fakeStaff, 'students')), false);
  await t('Sahte personel öğrenci SİLEMEZ', deleteDoc(doc(fakeStaff, 'students/S1')), false);
  await t('Sahte personel kendini dizine YAZAMAZ', setDoc(doc(fakeStaff, 'idx_staff/9999'), { no: '9999', lvl: 'admin' }), false);
  await t('Sahte öğrenci mesajları OKUYAMAZ', getDocs(collection(fakeStu, 'messages')), false);
  await t('Sahte öğrenci yoklama YAZAMAZ', addDoc(collection(fakeStu, 'attendance'), { x: 1 }), false);
  await t('Girişsiz ziyaretçi öğrencileri okuyamaz', getDocs(collection(anon, 'students')), false);
  // Gerçek kullanıcılar
  await t('Yönetici öğrencileri okur', getDocs(collection(admin, 'students')), true);
  await t('Yönetici öğretmen ekler', setDoc(doc(admin, 'teachers/T3'), { no: '12202601', name: 'Nû' }), true);
  await t('Yönetici dizine yazar', setDoc(doc(admin, 'idx_staff/12202601'), { no: '12202601', lvl: 'teacher' }), true);
  await t('Öğretmen öğrencileri okur', getDocs(collection(teacher, 'students')), true);
  await t('Öğretmen öğretmen listesini okur', getDocs(collection(teacher, 'teachers')), true);
  await t('Öğretmen kendini YÖNETİCİ yapamaz', updateDoc(doc(teacher, 'teachers/T2'), { isAdmin: true }), false);
  await t('Öğretmen kendi telefonunu düzenler', updateDoc(doc(teacher, 'teachers/T2'), { phone: '555' }), true);
  await t('Öğretmen başka öğretmeni SİLEMEZ', deleteDoc(doc(teacher, 'teachers/T1')), false);
  await t('Öğretmen dizine YAZAMAZ', setDoc(doc(teacher, 'idx_staff/11202601'), { lvl: 'admin' }), false);
  await t('Öğretmen duyuru yazar', addDoc(collection(teacher, 'announcements'), { t: 1 }), true);
  await t('Öğrenci kendi kaydını sorgular (no==)', getDocs(query(collection(student, 'students'), where('no', '==', '10202601'))), true);
  await t('Öğrenci başka öğrenciyi OKUYAMAZ', getDoc(doc(student, 'students/S2')), false);
  await t('Öğrenci tüm listeyi OKUYAMAZ', getDocs(collection(student, 'students')), false);
  await t('Öğrenci kendi telefonunu düzenler', updateDoc(doc(student, 'students/S1'), { phone: '555' }), true);
  await t('Öğrenci kendi ALANINI değiştiremez', updateDoc(doc(student, 'students/S1'), { area: 'muzik' }), false);
  await t('Öğrenci program okur', getDocs(collection(student, 'schedule')), true);
  await t('Öğrenci KENDİ yoklamasını yazar (QR)', setDoc(doc(student, 'attendance/s1_x'), { sessionId: 's1', studentNo: '10202601' }), true);
  await t('Öğrenci BAŞKASI adına yoklama yazamaz', setDoc(doc(student, 'attendance/s1_y'), { sessionId: 's1', studentNo: '10202602' }), false);
  await t('Öğrenci yoklama SİLEMEZ', deleteDoc(doc(student, 'attendance/s1_x')), false);
  await t('Öğrenci program YAZAMAZ', addDoc(collection(student, 'schedule'), { x: 1 }), false);
  await t('Öğrenci roller YAZAMAZ', setDoc(doc(student, 'roles/uid-10202601@ogrenci.aat'), { role: 'teacher' }), false);
  // Zarok (veli)
  const veli = as('92026001@veli.aat'), fakeVeli = as('99999999@veli.aat');
  const { arrayUnion } = require('firebase/firestore');
  await t('Veli KENDİ çocuğunu okur', getDoc(doc(veli, 'kids/K1')), true);
  await t('Veli çocuklarını sorgular (array-contains)', getDocs(query(collection(veli, 'kids'), where('guardianNos', 'array-contains', '92026001'))), true);
  await t('Veli BAŞKA çocuğu okuyamaz', getDoc(doc(veli, 'kids/K2')), false);
  await t('Veli tüm çocuk listesini okuyamaz', getDocs(collection(veli, 'kids')), false);
  await t('Veli çocuğunun yoklamasını okur', getDocs(query(collection(veli, 'kidAttendance'), where('guardianNos', 'array-contains', '92026001'))), true);
  await t('Veli başka çocuğun yoklamasını okuyamaz', getDoc(doc(veli, 'kidAttendance/A2')), false);
  await t('Veli yoklama YAZAMAZ', addDoc(collection(veli, 'kidAttendance'), { kidId: 'K1', guardianNos: ['92026001'] }), false);
  await t('Veli teslim listesini günceller', updateDoc(doc(veli, 'kids/K1'), { pickups: ['Dayî'] }), true);
  await t('Veli çocuğa başka veli EKLEYEMEZ', updateDoc(doc(veli, 'kids/K1'), { guardianNos: arrayUnion('99999999') }), false);
  await t('Veli yetişkin öğrencileri OKUYAMAZ', getDocs(collection(veli, 'students')), false);
  await t('Veli yetişkin mesajlarını OKUYAMAZ', getDocs(collection(veli, 'messages')), false);
  await t('Veli program ve duyuru okur', getDocs(collection(veli, 'kidSchedule')), true);
  await t('Veli mesaj gönderir', addDoc(collection(veli, 'kidMessages'), { guardianNo: '92026001', text: 'Silav', from: 'guardian', read: false }), true);
  await t('Veli başka veli adına mesaj yazamaz', addDoc(collection(veli, 'kidMessages'), { guardianNo: '92026002', text: 'x', from: 'guardian' }), false);
  await t('Veli başkasının mesajını okuyamaz', getDoc(doc(veli, 'kidMessages/M1')), false);
  await t('Sahte veli çocukları OKUYAMAZ', getDocs(query(collection(fakeVeli, 'kids'), where('guardianNos', 'array-contains', '99999999'))), false);
  await t('Sahte veli program okuyamaz', getDocs(collection(fakeVeli, 'kidSchedule')), false);
  await t('Bağlanmamış akademi öğretmeni çocuk yoklaması YAZAMAZ', addDoc(collection(teacher, 'kidAttendance'), { kidId: 'K1', guardianNos: ['92026001'], type: 'in' }), false);
  await t('Bağlanmamış akademi öğretmeni çocukları OKUYAMAZ', getDocs(collection(teacher, 'kids')), false);
  const linkedT = as('21202601@ogretmen.aat');
  await t('Çocuk akademisine bağlı akademi öğretmeni yoklama yazar', addDoc(collection(linkedT, 'kidAttendance'), { kidId: 'K1', guardianNos: ['92026001'], type: 'in' }), true);
  await t('Çocuk akademisine bağlı akademi öğretmeni çocukları okur', getDocs(collection(linkedT, 'kids')), true);
  await t('Öğretmen çocuk kaydı AÇAMAZ (yalnız yönetici)', setDoc(doc(teacher, 'kids/K9'), { no: '1', guardianNos: [] }), false);
  await t('Yönetici çocuk + veli kaydı açar', setDoc(doc(admin, 'kids/K9'), { no: '82026009', guardianNos: ['92026009'] }), true);
  await t('Site veli başvurusu gönderir', addDoc(collection(anon, 'kidApplications'), { kidName: 'Zarok', guardianName: 'Veli', phone: '05', consentKvkk: true, status: 'new' }), true);
  await t('Site KVKK onaysız başvuru gönderemez', addDoc(collection(anon, 'kidApplications'), { kidName: 'Zarok', guardianName: 'Veli', phone: '05', consentKvkk: false, status: 'new' }), false);
  await t('Site başvuruya fazladan alan ekleyemez', addDoc(collection(anon, 'kidApplications'), { kidName: 'Zarok', guardianName: 'Veli', phone: '05', consentKvkk: true, status: 'accepted' }), false);
  await t('Site veli başvurularını okuyamaz', getDocs(collection(anon, 'kidApplications')), false);
  // Zarok öğretmeni
  const kt = as('72026001@zmamoste.aat'), fakeKt = as('79999999@zmamoste.aat');
  await t('Çocuk öğretmeni çocukları okur', getDocs(collection(kt, 'kids')), true);
  await t('Çocuk öğretmeni veli iletişimini okur', getDoc(doc(kt, 'guardians/92026001')), true);
  await t('Çocuk öğretmeni yoklama yazar', addDoc(collection(kt, 'kidAttendance'), { kidId: 'K1', guardianNos: ['92026001'], type: 'in' }), true);
  await t('Çocuk öğretmeni duyuru gönderir', addDoc(collection(kt, 'kidAnnouncements'), { title: 'x' }), true);
  await t('Çocuk öğretmeni veliye yanıt yazar', addDoc(collection(kt, 'kidMessages'), { guardianNo: '92026001', text: 'y', from: 'staff' }), true);
  await t('Çocuk öğretmeni yetişkin öğrencileri OKUYAMAZ', getDocs(collection(kt, 'students')), false);
  await t('Çocuk öğretmeni yetişkin mesajlarını OKUYAMAZ', getDocs(collection(kt, 'messages')), false);
  await t('Çocuk öğretmeni çocuk kaydı AÇAMAZ', setDoc(doc(kt, 'kids/K8'), { no: '1', guardianNos: [] }), false);
  await t('Çocuk öğretmeni öğretmen ekleyemez', setDoc(doc(kt, 'kidTeachers/7'), { no: '7' }), false);
  await t('Çocuk öğretmeni program DEĞİŞTİREMEZ', addDoc(collection(kt, 'kidSchedule'), { x: 1 }), false);
  await t('Sahte çocuk öğretmeni çocukları OKUYAMAZ', getDocs(collection(fakeKt, 'kids')), false);
  await t('Yönetici çocuk öğretmeni ekler', setDoc(doc(admin, 'kidTeachers/72026002'), { no: '72026002' }), true);
  await t('Zarok haberleri herkese açık', getDoc(doc(anon, 'kidNews/KN1')), true);
  await t('Girişsiz haber YAZAMAZ', addDoc(collection(anon, 'kidNews'), { title: 'x' }), false);
  await t('Öğretmen Zarok haberi YAZAMAZ (yalnız basın)', addDoc(collection(teacher, 'kidArchive'), { year: 2020 }), false);
  await t('Veli haber YAZAMAZ', addDoc(collection(veli, 'kidNews'), { title: 'x' }), false);
  // ── v5: rol ayrımı / yetki yükseltme ──
  const press = as('99202601@ogretmen.aat'), reg = as('98202601@ogretmen.aat');
  await t('Basın kendini dizinde YÖNETİCİ yapamaz', setDoc(doc(press, 'idx_staff/99202601'), { no: '99202601', lvl: 'admin' }), false);
  await t('Basın öğretmen EKLEYEMEZ', setDoc(doc(press, 'teachers/TX'), { no: '13202601', name: 'x' }), false);
  await t('Basın öğrenci SİLEMEZ', deleteDoc(doc(press, 'students/S2')), false);
  await t('Basın öğrenci EKLEYEMEZ', setDoc(doc(press, 'students/SX'), { no: '1', name: 'x' }), false);
  await t('Basın başvuruları OKUYAMAZ', getDocs(collection(press, 'applications')), false);
  await t('Basın veli başvurularını OKUYAMAZ', getDocs(collection(press, 'kidApplications')), false);
  await t('Basın çocuk kayıtlarını OKUYAMAZ', getDocs(collection(press, 'kids')), false);
  await t('Basın site haberi yazar', addDoc(collection(press, 'news'), { title: 'x' }), true);
  await t('Basın site arşivi yazar', addDoc(collection(press, 'archive'), { year: 2010 }), true);
  await t('Basın Zarok haberi yazar', addDoc(collection(press, 'kidNews'), { title: 'x' }), true);
  await t('Basın Zarok arşivi yazar', addDoc(collection(press, 'kidArchive'), { year: 2020 }), true);
  await t('Öğretmen site haberi YAZAMAZ', addDoc(collection(teacher, 'news'), { title: 'x' }), false);
  await t('Öğretmen başvuruları OKUYAMAZ', getDocs(collection(teacher, 'applications')), false);
  await t('Öğretmen başvuru dönemini DEĞİŞTİREMEZ', setDoc(doc(teacher, 'config/applications'), { open: false }), false);
  await t('Öğretmen öğrenci ekler', setDoc(doc(teacher, 'students/S9'), { no: '11202609', name: 'Yeni' }), true);
  await t('Öğretmen öğrenci SİLEMEZ', deleteDoc(doc(teacher, 'students/S2')), false);
  await t('Öğretmen öğrencinin bursunu DEĞİŞTİREMEZ', updateDoc(doc(teacher, 'students/S2'), { burs: '%100' }), false);
  await t('Öğrenci işleri kendini YÖNETİCİ yapamaz', setDoc(doc(reg, 'idx_staff/98202601'), { no: '98202601', lvl: 'admin' }), false);
  await t('Öğrenci işleri başkasını BASIN yapamaz', setDoc(doc(reg, 'idx_staff/11202601'), { no: '11202601', lvl: 'press' }), false);
  await t('Öğrenci işleri yönetici kaydını SİLEMEZ', deleteDoc(doc(reg, 'idx_staff/1000')), false);
  await t('Öğrenci işleri öğretmen dizinine yazar', setDoc(doc(reg, 'idx_staff/13202601'), { no: '13202601', lvl: 'teacher' }), true);
  await t('Öğrenci işleri özel kart (isAdmin) AÇAMAZ', setDoc(doc(reg, 'teachers/TY'), { no: '13202602', name: 'x', isAdmin: true }), false);
  await t('Öğrenci işleri basın kartını DEĞİŞTİREMEZ', updateDoc(doc(reg, 'teachers/TP'), { name: 'y' }), false);
  await t('Öğrenci işleri öğretmen ekler', setDoc(doc(reg, 'teachers/TZ'), { no: '13202601', name: 'Mamoste' }), true);
  await t('Öğrenci işleri öğrenci bursunu düzenler', updateDoc(doc(reg, 'students/S2'), { burs: '%50' }), true);
  await t('Öğrenci işleri başvuruları okur', getDocs(collection(reg, 'applications')), true);
  await t('Öğrenci işleri çocuk kaydı açar', setDoc(doc(reg, 'kids/K7'), { no: '82026007', guardianNos: ['92026001'] }), true);
  await t('Öğrenci işleri Zarok haberi YAZAMAZ (basının işi)', addDoc(collection(reg, 'kidNews'), { title: 'x' }), false);
  await t('Site çocuk başvurusu istenen belgelerini okur', getDocs(collection(anon, 'kidApplicationTemplates')), true);
  await t('Girişsiz istenen belge YAZAMAZ', addDoc(collection(anon, 'kidApplicationTemplates'), { name: 'x' }), false);
  await t('Öğretmen istenen belge YAZAMAZ', addDoc(collection(teacher, 'kidApplicationTemplates'), { name: 'x' }), false);
  await t('Öğrenci işleri istenen belge tanımlar', addDoc(collection(reg, 'kidApplicationTemplates'), { name: 'Nasname' }), true);
  // ── Kartlar + kapı güvenliği ──
  const gate = as('97202601@ogretmen.aat'), TA = 'cards/' + 'a'.repeat(32), TB = 'cards/' + 'b'.repeat(32);
  const today = new Date().toISOString().slice(0, 10);
  await t('Kapı görevlisi kartı anahtarla doğrular', getDoc(doc(gate, TA)), true);
  await t('Kapı görevlisi kartları LİSTELEYEMEZ (tahmin/tarama yok)', getDocs(collection(gate, 'cards')), false);
  await t('Kapı görevlisi öğrencileri OKUYAMAZ', getDocs(collection(gate, 'students')), false);
  await t('Kapı görevlisi öğretmen listesini OKUYAMAZ', getDocs(collection(gate, 'teachers')), false);
  await t('Kapı görevlisi kendi kaydını okur (giriş)', getDocs(query(collection(gate, 'teachers'), where('no', '==', '97202601'))), true);
  await t('Kapı görevlisi mesajları OKUYAMAZ', getDocs(collection(gate, 'messages')), false);
  await t('Kapı görevlisi çocuk kayıtlarını OKUYAMAZ', getDocs(collection(gate, 'kids')), false);
  await t('Kapı görevlisi başvuruları OKUYAMAZ', getDocs(collection(gate, 'applications')), false);
  await t('Kapı görevlisi duyuru YAZAMAZ', addDoc(collection(gate, 'announcements'), { t: 1 }), false);
  await t('Kapı görevlisi kart ÇIKARAMAZ', setDoc(doc(gate, 'cards/' + 'd'.repeat(32)), { kind: 'student', active: true }), false);
  await t('Kapı görevlisi giriş kaydı yazar (kendi adına)', addDoc(collection(gate, 'gateLog'), { token: 'a'.repeat(32), no: '10202601', kind: 'student', name: 'X', ok: true, by: '97202601', byName: 'E', date: today, place: 'gate' }), true);
  await t('Kapı görevlisi BAŞKASI adına kayıt yazamaz', addDoc(collection(gate, 'gateLog'), { token: 'x', ok: true, by: '11202601', date: today, place: 'gate' }), false);
  await t('Giriş kaydına fazladan alan eklenemez', addDoc(collection(gate, 'gateLog'), { token: 'x', ok: true, by: '97202601', date: today, place: 'gate', admin: true }), false);
  await t('Kapı görevlisi kendi bugünkü kayıtlarını okur', getDocs(query(collection(gate, 'gateLog'), where('by', '==', '97202601'), where('date', '==', today))), true);
  await t('Kapı görevlisi başkasının kayıtlarını OKUYAMAZ', getDoc(doc(gate, 'gateLog/G1')), false);
  await t('Giriş kaydı DEĞİŞTİRİLEMEZ', updateDoc(doc(gate, 'gateLog/G1'), { ok: false }), false);
  await t('Öğretmen kartı doğrular (derse giriş)', getDoc(doc(teacher, TA)), true);
  await t('Öğretmen kart ÇIKARAMAZ', setDoc(doc(teacher, 'cards/' + 'e'.repeat(32)), { kind: 'student', active: true }), false);
  await t('Öğrenci kart okuyamaz', getDoc(doc(student, TA)), false);
  await t('Öğrenci kendi kart anahtarını DEĞİŞTİREMEZ', updateDoc(doc(student, 'students/S1'), { cardToken: 'f'.repeat(32) }), false);
  await t('Veli kart okuyamaz', getDoc(doc(veli, TB)), false);
  await t('Girişsiz kart okuyamaz', getDoc(doc(anon, TA)), false);
  await t('Çocuk öğretmeni çocuk kartını doğrular', getDoc(doc(kt, TB)), true);
  await t('Çocuk öğretmeni yetişkin kartını OKUYAMAZ', getDoc(doc(kt, TA)), false);
  await t('Öğrenci işleri kart çıkarır', setDoc(doc(reg, 'cards/' + 'e'.repeat(32)), { kind: 'student', no: '10202602', active: true }), true);
  await t('Öğrenci işleri kartı iptal eder', updateDoc(doc(reg, 'cards/' + 'e'.repeat(32)), { active: false }), true);
  await t('Öğrenci işleri öğrenciye kart anahtarı yazar', updateDoc(doc(reg, 'students/S2'), { cardToken: 'e'.repeat(32) }), true);
  await t('Öğrenci işleri giriş kayıtlarını okur', getDocs(collection(reg, 'gateLog')), true);
  await t('Öğrenci işleri güvenlik kartı (isGate) AÇAMAZ', setDoc(doc(reg, 'teachers/TQ'), { no: '97202699', name: 'x', isGate: true }), false);
  await t('Öğrenci işleri dizine "gate" yazamaz', setDoc(doc(reg, 'idx_staff/97202699'), { no: '97202699', lvl: 'gate' }), false);
  // Mesaj gizliliği
  await t('Öğrenci KENDİNE gelen özel mesajları sorgular', getDocs(query(collection(student, 'messages'), where('recipientNo', '==', '10202601'))), true);
  await t('Öğrenci BAŞKASININ özel mesajını okuyamaz', getDoc(doc(student, 'messages/M3')), false);
  await t('Öğrenci toplu öğrenci mesajlarını sorgular', getDocs(query(collection(student, 'messages'), where('recipientGroup', 'in', ['allStudents', 'all', 'area_sinema']))), true);
  await t('Öğrenci öğretmenlere yönelik toplu mesajı okuyamaz', getDoc(doc(student, 'messages/M5')), false);
  await t('Öğrenci tüm mesajları listeleyemez', getDocs(collection(student, 'messages')), false);
  await t('Öğrenci yönetime geri bildirim gönderir', addDoc(collection(student, 'messages'), { fromType: 'student', toRole: 'admin', subject: 's', body: 'b' }), true);
  await t('Öğrenci YÖNETİCİ adına toplu mesaj gönderemez', addDoc(collection(student, 'messages'), { fromType: 'admin', senderId: 'admin', recipientGroup: 'allStudents', subject: 'Şifrenizi girin', body: 'x' }), false);
  await t('Öğrenci başka öğrencinin mesajını SİLEMEZ', deleteDoc(doc(student, 'messages/M3')), false);
  await t('Öğrenci kendi mesajını okundu işaretler', updateDoc(doc(student, 'messages/M2'), { read: true }), true);
  await t('Öğrenci KENDİ anket yanıtını yazar', setDoc(doc(student, 'studentSurveyResponses/R1'), { studentNo: '10202601', answers: {} }), true);
  await t('Öğrenci başkasının anket yanıtını OKUYAMAZ', getDoc(doc(student, 'studentSurveyResponses/R2')), false);
  await t('Öğrenci başkası adına anket yanıtı YAZAMAZ', setDoc(doc(student, 'studentSurveyResponses/R3'), { studentNo: '10202602', answers: {} }), false);
  await t('Öğrenci başkasının cihaz kaydını DEĞİŞTİREMEZ', setDoc(doc(student, 'devices/10202602'), { no: 'x' }), false);
  await t('Öğrenci kendi cihaz kaydını yazar', setDoc(doc(student, 'devices/10202601'), { no: '10202601' }), true);
  await t('Öğrenci başkalarının istatistiklerini OKUYAMAZ', getDocs(collection(student, 'studentStats')), false);
  // Site
  await t('Site haberleri herkese açık', getDoc(doc(anon, 'news/N1')), true);
  await t('Site başvuru gönderir (dönem açık)', addDoc(collection(anon, 'applications'), { name: 'A', phone: '1', status: 'new', docs: [] }), true);
  await t('Site başvuru okuyamaz', getDocs(collection(anon, 'applications')), false);
  // Storage
  const st = e => env.authenticatedContext('uid-' + e, { email: e }).storage();
  const png = 'data:image/png;base64,iVBORw0KGgo=';
  await t('Storage: sahte personel haber medyası YÜKLEYEMEZ', uploadString(ref(st('9999@ogretmen.aat'), 'news/x.png'), png, 'data_url'), false);
  await t('Storage: öğretmen haber medyası YÜKLEYEMEZ (yalnız basın)', uploadString(ref(st('11202601@ogretmen.aat'), 'news/x.png'), png, 'data_url'), false);
  await t('Storage: basın haber medyası yükler', uploadString(ref(st('99202601@ogretmen.aat'), 'news/x.png'), png, 'data_url'), true);
  await t('Storage: basın HTML dosyası yükleyemez', uploadString(ref(st('99202601@ogretmen.aat'), 'news/x.html'), 'data:text/html;base64,PHNjcmlwdD4=', 'data_url'), false);
  await t('Storage: basın SVG yükleyemez', uploadString(ref(st('99202601@ogretmen.aat'), 'news/x.svg'), 'data:image/svg+xml;base64,PHN2Zz4=', 'data_url'), false);
  await t('Storage: öğrenci profil fotoğrafı yükler', uploadString(ref(st('10202601@ogrenci.aat'), 'photos/students/S1.jpg'), png, 'data_url'), true);
  await t('Storage: öğrenci BAŞKASININ fotoğrafını yükleyemez', uploadString(ref(st('10202601@ogrenci.aat'), 'photos/students/S2.jpg'), png, 'data_url'), false);
  await t('Storage: basın Zarok haber görseli yükler', uploadString(ref(st('99202601@ogretmen.aat'), 'kid-news/a.png'), png, 'data_url'), true);
  await t('Storage: öğretmen Zarok haber görseli YÜKLEYEMEZ', uploadString(ref(st('11202601@ogretmen.aat'), 'kid-news/c.png'), png, 'data_url'), false);
  await t('Storage: girişsiz Zarok haber görseli yükleyemez', uploadString(ref(env.unauthenticatedContext().storage(), 'kid-news/b.png'), png, 'data_url'), false);
  await t('Storage: veli başvuru belgesi yükler', uploadString(ref(env.unauthenticatedContext().storage(), 'zarok-applications/a.pdf'), 'data:application/pdf;base64,JVBERi0=', 'data_url'), true);
  await t('Storage: öğretmen KENDİ fotoğrafını yükler', uploadString(ref(st('11202601@ogretmen.aat'), 'photos/teachers/T2.jpg'), png, 'data_url'), true);
  await t('Storage: öğretmen yöneticinin fotoğrafını DEĞİŞTİREMEZ', uploadString(ref(st('11202601@ogretmen.aat'), 'photos/teachers/T1.jpg'), png, 'data_url'), false);
  await t('Storage: sahte öğrenci foto YÜKLEYEMEZ', uploadString(ref(st('7777@ogrenci.aat'), 'photos/students/S1.jpg'), png, 'data_url'), false);
  await t('Storage: girişsiz başvuru PDF yükler', uploadString(ref(env.unauthenticatedContext().storage(), 'applications/a.pdf'), 'data:application/pdf;base64,JVBERi0=', 'data_url'), true);
  await t('Storage: girişsiz başvuru EXE yükleyemez', uploadString(ref(env.unauthenticatedContext().storage(), 'applications/a.exe'), 'data:application/octet-stream;base64,TVo=', 'data_url'), false);
  // Sınıflar (ana akademi + çocuk akademisi)
  const cReg = as('98202601@ogretmen.aat'), cTch = as('11202601@ogretmen.aat'), cStu = as('10202601@ogrenci.aat'), cVel = as('92026001@veli.aat'), cKidT = as('72026001@zmamoste.aat');
  await t('Sınıf: öğrenci işleri sınıf öğretmeni atar', setDoc(doc(cReg, 'classes/muzik_1'), { area: 'muzik', level: 1, teacherNos: ['11202601'], teacherNames: ['Mamoste'] }), true);
  await t('Sınıf: öğretmen sınıfları okur', getDocs(collection(cTch, 'classes')), true);
  await t('Sınıf: öğrenci sınıf öğretmenini okur', getDoc(doc(cStu, 'classes/muzik_1')), true);
  await t('Sınıf: öğretmen sınıf YAZAMAZ', setDoc(doc(cTch, 'classes/muzik_1'), { teacherNos: [] }), false);
  await t('Sınıf: öğrenci sınıf YAZAMAZ', setDoc(doc(cStu, 'classes/muzik_2'), { teacherNos: ['x'] }), false);
  await t('Sınıf: öğrenci KENDİ sınıfını değiştiremez', updateDoc(doc(cStu, 'students/S1'), { classLevel: 4 }), false);
  await t('Sınıf: veli akademi sınıflarını OKUYAMAZ', getDocs(collection(cVel, 'classes')), false);
  await t('Sınıf: girişsiz okuyamaz', getDocs(collection(env.unauthenticatedContext().firestore(), 'classes')), false);
  await t('Çocuk sınıfı: öğrenci işleri sınıf öğretmeni atar', setDoc(doc(cReg, 'kidClasses/L1'), { level: 1, teacherNos: ['72026001'], teacherNames: ['Mamoste Hêvî'] }), true);
  await t('Çocuk sınıfı: veli okur (sınıf öğretmeni adı)', getDoc(doc(cVel, 'kidClasses/L1')), true);
  await t('Çocuk sınıfı: çocuk öğretmeni okur', getDocs(collection(cKidT, 'kidClasses')), true);
  await t('Çocuk sınıfı: veli YAZAMAZ', setDoc(doc(cVel, 'kidClasses/L1'), { teacherNos: [] }), false);
  await t('Çocuk sınıfı: çocuk öğretmeni YAZAMAZ', setDoc(doc(cKidT, 'kidClasses/L2'), { teacherNos: ['72026001'] }), false);
  await t('Çocuk sınıfı: veli çocuğunun sınıfını değiştiremez', updateDoc(doc(cVel, 'kids/K1'), { classLevel: 3 }), false);
  await t('Çocuk sınıfı: öğrenci (yetişkin) okuyamaz', getDocs(collection(cStu, 'kidClasses')), false);
  await t('Çocuk sınıfı: öğrenci işleri çocuğun sınıfını değiştirir', updateDoc(doc(cReg, 'kids/K1'), { classLevel: 2 }), true);
  // Sınıf paylaşımları (duyuru/ödev/belge)
  const cT2 = as('11202601@ogretmen.aat'), cT3 = as('21202601@ogretmen.aat'), cS = as('10202601@ogrenci.aat'), cV = as('92026001@veli.aat'), cKT = as('72026001@zmamoste.aat'), cR = as('98202601@ogretmen.aat');
  const post = (no, cid, x) => ({ classId: cid, area: 'muzik', level: 1, type: 'odev', title: 'Erk', body: '', due: '', files: [], teacherNo: no, teacherName: 'M', createdAt: new Date(), ...(x || {}) });
  await t('Paylaşım: sınıf öğretmeni KENDİ sınıfına ödev gönderir', setDoc(doc(cT2, 'classPosts/P1'), post('11202601', 'muzik_1')), true);
  await t('Paylaşım: öğretmen BAŞKA sınıfa gönderemez', setDoc(doc(cT3, 'classPosts/P2'), post('21202601', 'muzik_1')), false);
  await t('Paylaşım: öğretmen başkası adına gönderemez', setDoc(doc(cT3, 'classPosts/P3'), post('11202601', 'muzik_1')), false);
  await t('Paylaşım: olmayan sınıfa gönderilemez', setDoc(doc(cT2, 'classPosts/P4'), post('11202601', 'sinema_3')), false);
  await t('Paylaşım: geçersiz tür reddedilir', setDoc(doc(cT2, 'classPosts/P5'), post('11202601', 'muzik_1', { type: 'x' })), false);
  await t('Paylaşım: öğrenci okur', getDoc(doc(cS, 'classPosts/P1')), true);
  await t('Paylaşım: öğrenci YAZAMAZ', setDoc(doc(cS, 'classPosts/P6'), post('10202601', 'muzik_1')), false);
  await t('Paylaşım: başka öğretmen SİLEMEZ', deleteDoc(doc(cT3, 'classPosts/P1')), false);
  await t('Paylaşım: veli akademi paylaşımlarını OKUYAMAZ', getDoc(doc(cV, 'classPosts/P1')), false);
  await t('Paylaşım: öğretmen kendi paylaşımını siler', deleteDoc(doc(cT2, 'classPosts/P1')), true);
  await t('Çocuk paylaşımı: sınıf öğretmeni gönderir', setDoc(doc(cKT, 'kidClassPosts/Q1'), post('72026001', 'L1')), true);
  await t('Çocuk paylaşımı: sınıfı olmayan öğretmen gönderemez', setDoc(doc(cKT, 'kidClassPosts/Q2'), post('72026001', 'L2')), false);
  await t('Çocuk paylaşımı: veli okur', getDoc(doc(cV, 'kidClassPosts/Q1')), true);
  await t('Çocuk paylaşımı: veli YAZAMAZ', setDoc(doc(cV, 'kidClassPosts/Q3'), post('92026001', 'L1')), false);
  await t('Çocuk paylaşımı: yetişkin öğrenci okuyamaz', getDoc(doc(cS, 'kidClassPosts/Q1')), false);
  await t('Çocuk paylaşımı: öğrenci işleri siler', deleteDoc(doc(cR, 'kidClassPosts/Q1')), true);
  // Veli anketleri
  const sgA = as('92026001@veli.aat'), sgB = as('92026002@veli.aat'), sgR = as('98202601@ogretmen.aat'), sgK = as('72026001@zmamoste.aat'), sgS = as('10202601@ogrenci.aat');
  const resp = (sid, no, x) => ({ surveyId: sid, guardianNo: no, guardianName: 'V', kidLevels: [1], answers: { q1: 5 }, submittedAt: '2026-10-04', ...(x || {}) });
  await t('Veli anketi: öğrenci işleri oluşturur', setDoc(doc(sgR, 'kidSurveys/S1'), { title: 'Razîbûn', active: true, questions: [{ id: 'q1', type: 'likert', text: 'x' }] }), true);
  await t('Veli anketi: kapalı anket oluşturulur', setDoc(doc(sgR, 'kidSurveys/S2'), { title: 'Reşnivîs', active: false, questions: [] }), true);
  await t('Veli anketi: veli okur', getDoc(doc(sgA, 'kidSurveys/S1')), true);
  await t('Veli anketi: veli anket YAZAMAZ', setDoc(doc(sgA, 'kidSurveys/S3'), { title: 'x', active: true }), false);
  await t('Veli anketi: çocuk öğretmeni anket YAZAMAZ', setDoc(doc(sgK, 'kidSurveys/S3'), { title: 'x', active: true }), false);
  await t('Veli anketi: yetişkin öğrenci okuyamaz', getDoc(doc(sgS, 'kidSurveys/S1')), false);
  await t('Veli yanıtı: veli kendi adına yanıtlar', setDoc(doc(sgA, 'kidSurveyResponses/S1_92026001'), resp('S1', '92026001')), true);
  await t('Veli yanıtı: veli yanıtını günceller', setDoc(doc(sgA, 'kidSurveyResponses/S1_92026001'), resp('S1', '92026001', { answers: { q1: 4 } })), true);
  await t('Veli yanıtı: başka veli adına yanıtlayamaz', setDoc(doc(sgA, 'kidSurveyResponses/S1_92026002'), resp('S1', '92026002')), false);
  await t('Veli yanıtı: belge kimliği uydurulamaz', setDoc(doc(sgA, 'kidSurveyResponses/X_92026001'), resp('S1', '92026001')), false);
  await t('Veli yanıtı: kapalı ankete yanıt verilemez', setDoc(doc(sgA, 'kidSurveyResponses/S2_92026001'), resp('S2', '92026001')), false);
  await t('Veli yanıtı: fazladan alan reddedilir', setDoc(doc(sgA, 'kidSurveyResponses/S1_92026001'), resp('S1', '92026001', { isAdmin: true })), false);
  await t('Veli yanıtı: başka velinin yanıtını OKUYAMAZ', getDoc(doc(sgB, 'kidSurveyResponses/S1_92026001')), false);
  await t('Veli yanıtı: kendi yanıtını okur', getDoc(doc(sgA, 'kidSurveyResponses/S1_92026001')), true);
  await t('Veli yanıtı: öğrenci işleri sonuçları okur', getDocs(collection(sgR, 'kidSurveyResponses')), true);
  await t('Veli yanıtı: çocuk öğretmeni sonuçları okuyamaz', getDocs(collection(sgK, 'kidSurveyResponses')), false);
  console.log(results.join('\n'));
  console.log(results.filter(r => r.startsWith('❌')).length + ' başarısız / ' + results.length);
  await env.cleanup();
  process.exit(0);
})();
